window.DISEASE = (function () {
  const meta = { id:"ad", title: "Alzheimer's Disease (AD)", domain: "Neuro", updated: "2026-09-15", searchPlaceholder: "Search: amyloid, APOE, p-tau217, ARIA" };
  const acts = [
    { id:"A", num: "01", en: "DEFINITION · EPIDEMIOLOGY", title: "무엇인가", accent: "#6f3a55", blurb: "정의·생물학적 단계 · 아형·감별 · 세계와 한국의 규모 · 질병부담", sections: ["def", "epi"] },
    { id:"B", num: "02", en: "CAUSE · COURSE", title: "왜·어떻게", accent: "#315d78", blurb: "유전·비유전 위험 · APOE · amyloid·tau · microglia·혈관 · 이질적 진행", sections: ["risk", "course"] },
    { id:"C", num: "03", en: "CLINICAL", title: "임상", accent: "#94553b", blurb: "초기 증상 · 2024 생물학적 진단 · 체액·영상 바이오마커 · 증상·질병조절 치료", sections: ["dx", "tx"] },
    { id:"D", num: "04", en: "RESEARCH", title: "연구", accent: "#1f5d43", blurb: "GWAS·PRS · 단일세포·QTL · 새 치료제·코호트·분석 기법 · 전이성 검증", sections: ["omics", "now"] }
  ];
  const sections = {
    def: { number: "01", title: "정의 · 분류", act: "A", questions: [
      { q: "어떻게 정의하고 치매와 구분하는가?", note: "생물학적 AD · 임상 증후군 dementia 분리", article: "ckd-definition" },
      { q: "임상·생물학적 단계는 어떻게 나누는가?", note: "무증상 병리 → MCI → 경증·중등도·중증 치매", article: "ckd-stages" },
      { q: "주요 아형과 감별 질환은 무엇인가?", note: "조기·후기 발병 · 가족성·산발성 · 혼합병리", article: "ckd-subtypes" }
    ]},
    epi: { number: "02", title: "역학 · 질병부담", act: "A", questions: [
      { q: "세계와 한국에서 얼마나 흔한가?", note: "AD 단독 · 전체 치매 · 한국 청구자료의 분모 구분", article: "ckd-prevalence" },
      { q: "환자 수와 발생은 어떻게 변하는가?", note: "고령화 → 절대 환자 증가 · 연령표준화 지표 분리", article: "ckd-trend" },
      { q: "연령·성별·지역별 차이는 무엇인가?", note: "고령 급증 · 여성 부담 · 지역·방법 차이", article: "ckd-demographics" },
      { q: "질병부담과 돌봄 비용은 얼마나 큰가?", note: "DALY · 사망 · 비공식 돌봄 · 사회적 비용", article: "ckd-burden" }
    ]},
    risk: { number: "01", title: "원인 · 위험인자", act: "B", questions: [
      { q: "유전 위험은 얼마나 큰가?", note: "heritability 60–80% · 다유전자 구조 · missing heritability", article: "ckd-heritability" },
      { q: "APOE와 희귀 고침투 변이는 어떻게 다른가?", note: "APOE ε4 · APP·PSEN1·PSEN2 · 보호 변이", article: "ckd-apoe-rare" },
      { q: "비유전 위험·보호요인은 무엇인가?", note: "노화 · 혈관 위험 · 생활·환경 · 경로 분리", article: "ckd-nongenetic-risk" },
      { q: "ancestry와 가족력은 위험 해석을 어떻게 바꾸는가?", note: "European 편중 · LD·대립유전자 빈도 · 가족성 구분", article: "ckd-ancestry-family" }
    ]},
    course: { number: "02", title: "발병 · 진행", act: "B", questions: [
      { q: "병리 변화는 증상보다 얼마나 먼저 시작되는가?", note: "biomarker 선행 → 무증상 구간 → 임상 발현", article: "ckd-preclinical" },
      { q: "amyloid·tau·신경퇴행은 어떤 순서로 진행하는가?", note: "A/T/N 축 · 비선형 진행 · biomarker와 증상 분리", article: "ckd-atn-course" },
      { q: "microglia·혈관·경계 면역은 진행에 어떻게 관여하는가?", note: "APOE·TREM2 · endothelial · meningeal lymphatic", article: "ckd-neuroimmune-course" },
      { q: "진행 속도와 회복탄력성은 왜 다른가?", note: "유전 배경 · cell state · 혼합병리 · 인지 예비력", article: "ckd-heterogeneity" }
    ]},
    dx: { number: "01", title: "진단 · 분류", act: "C", questions: [
      { q: "초기 증상과 경고 신호는 무엇인가?", note: "episodic memory · 언어·시공간 비전형 표현형 · 기능 저하", article: "ckd-symptoms" },
      { q: "최신 진단 기준은 무엇인가?", note: "2024 revised criteria · Core 1 biomarker · 생물학적 staging", article: "ckd-criteria" },
      { q: "혈액·CSF·PET·MRI 바이오마커를 어떻게 조합하는가?", note: "p-tau217/181 · Aβ42/40 · amyloid/tau PET · MRI", article: "ckd-biomarkers" },
      { q: "치매 아형과 가역적 원인을 어떻게 감별하는가?", note: "혈관성 · Lewy body · FTD · 약물·대사·정신질환", article: "ckd-differential" }
    ]},
    tx: { number: "02", title: "치료 · 미충족 수요", act: "C", questions: [
      { q: "표준 증상 치료와 비약물 관리는 무엇인가?", note: "AChE inhibitor · memantine · 기능·돌봄 지원", article: "ckd-standard-care" },
      { q: "anti-amyloid 항체는 누구에게 적용하는가?", note: "초기 증상 · amyloid 확인 · MRI·APOE 안전성 평가", article: "ckd-antiamyloid-eligibility" },
      { q: "lecanemab과 donanemab은 진행을 얼마나 늦추는가?", note: "18개월 상대 감속 · 척도·집단 차이 · 직접 비교 금지", article: "ckd-treatment-effect" },
      { q: "ARIA와 치료 안전성을 어떻게 관리하는가?", note: "ARIA-E·H · APOE ε4 · 항응고제 · 반복 MRI", article: "ckd-aria" },
      { q: "치료반응과 접근성의 미충족 수요는 무엇인가?", note: "modest benefit · 선별·주입·MRI 인프라 · 장기효과", article: "ckd-unmet" }
    ]},
    omics: { number: "01", title: "유전학 · 오믹스", act: "D", questions: [
      { q: "GWAS는 어떤 loci와 경로를 지목하는가?", note: "75 loci · amyloid/tau · endocytosis · microglia·면역", article: "ckd-gwas" },
      { q: "APOE 외 polygenic risk는 무엇을 더하는가?", note: "83변이 GRS · 발병·MCI 전환 · 소폭 예측 개선", article: "ckd-prs" },
      { q: "위험변이는 어떤 세포에서 작동하는가?", note: "microglia enrichment · non-neuron caQTL · 세포특이 조절", article: "ckd-variant-celltype" },
      { q: "bulk와 single-cell 연구는 무엇을 보여주는가?", note: "세포조성 교란 · cell-type-specific 반응 · 다영역 atlas", article: "ckd-singlecell" },
      { q: "혈관·microglia 신호와 임상표현형을 어떻게 연결하는가?", note: "endothelial loss · PGS · microglia state · 인과 검증", article: "ckd-vascular-microglia" }
    ]},
    now: { number: "02", title: "최신 동향", act: "D", questions: [
      { q: "진단 기준과 진료 권고는 최근 어떻게 바뀌었는가?", note: "2018 AT(N) → 2024 revised criteria · DETeCD-ADRD", article: "ckd-guideline-change" },
      { q: "새 치료제와 승인 현황은 무엇인가?", note: "lecanemab · donanemab · 국가별 허가·대상 차이", article: "ckd-drug-update" },
      { q: "새 코호트·아틀라스·QTL 자원은 무엇이 생겼는가?", note: "EADB · brainSCOPE · 다영역 single-cell · 한국 자원", article: "ckd-new-data" },
      { q: "새로 쓸 수 있게 된 분석 기법은 무엇인가?", note: "scQTL·caQTL · coloc · methylation deconvolution · spatial", article: "ckd-new-method" },
      { q: "인간·마우스·ancestry 전이성은 어떻게 검증하는가?", note: "human validation · cross-ancestry · 외부 코호트 재현", article: "ckd-transferability" }
    ]}
  };
  const P = {
    scheltens: ["Scheltens et al. 2021, Lancet 397:1577–1590", "https://doi.org/10.1016/S0140-6736(20)32205-4"],
    criteria: ["Jack et al. 2024, Alzheimer's & Dementia 20:5143–5169", "https://doi.org/10.1002/alz.13859"],
    gbdForecast: ["GBD 2019 Dementia Forecasting Collaborators 2022, Lancet Public Health 7:e105–e125", "https://doi.org/10.1016/S2468-2667(21)00249-8"],
    gbdBurden: ["GBD 2016 Dementia Collaborators 2019, Lancet Neurol 18:88–106", "https://doi.org/10.1016/S1474-4422(18)30403-4"],
    globalAD: ["Gustavsson et al. 2023, Alzheimer's & Dementia 19:658–670", "https://doi.org/10.1002/alz.12694"],
    korea: ["Baek et al. 2022, Front Neurol 13:883549", "https://doi.org/10.3389/fneur.2022.883549"],
    koreaHira: ["Kim et al. 2025, Yonsei Med J 66:590–598", "https://doi.org/10.3349/ymj.2024.0303"],
    bellenguez: ["Bellenguez et al. 2022, Nat Genet 54:412–436", "https://doi.org/10.1038/s41588-022-01024-z"],
    mathys: ["Mathys et al. 2019, Nature 570:332–337", "https://doi.org/10.1038/s41586-019-1195-2"],
    mathys2024: ["Mathys et al. 2024, Nature 632:858–868", "https://doi.org/10.1038/s41586-024-07606-7"],
    emani: ["Emani et al. 2024, Science 384:eadi5199", "https://doi.org/10.1126/science.adi5199"],
    zeng: ["Zeng et al. 2024, Science 384:eadh4265", "https://doi.org/10.1126/science.adh4265"],
    yap: ["Yap et al. 2024, Sci Adv 10:eadn7655", "https://doi.org/10.1126/sciadv.adn7655"],
    lecanemab: ["van Dyck et al. 2023, N Engl J Med 388:9–21", "https://doi.org/10.1056/NEJMoa2212948"],
    donanemab: ["Sims et al. 2023, JAMA 330:512–527", "https://doi.org/10.1001/jama.2023.13239"],
    memantine: ["Reisberg et al. 2003, N Engl J Med 348:1333–1341", "https://doi.org/10.1056/NEJMoa013128"],
    nice: ["NICE NG97 2018, last reviewed 2025", "https://www.nice.org.uk/guidance/ng97"],
    murdock: ["Murdock et al. 2024, Nature 627:149–156", "https://doi.org/10.1038/s41586-024-07132-6"],
    romero: ["Hitpass Romero et al. 2025, J Neuroinflammation 22:109", "https://doi.org/10.1186/s12974-025-03436-0"],
    lecanemabAur: ["Cummings et al. 2023, J Prev Alzheimers Dis 10:362–377", "https://doi.org/10.14283/jpad.2023.30"],
    donanemabAur: ["Rabinovici et al. 2025, J Prev Alzheimers Dis 12:100150", "https://doi.org/10.1016/j.tjpad.2025.100150"]
  };
  const articleList = [
    { id: "ckd-definition", section: "def", title: "어떻게 정의하고 치매와 구분하는가?",
      aliases: ["Alzheimer's disease","알츠하이머병","dementia","치매","biological definition"],
      summary: "AD는 amyloid·tau 병리로 규정되는 질환 과정 · dementia는 일상 기능을 침범한 임상 증후군 — 동의어 사용 금지",
      facts: [["질환 핵심","amyloid-β와 tau 병리","Jack et al.","2024",false],["임상 범위","무증상 생물학적 단계부터 치매 단계까지","Jack et al.","2024",false],["치매 중 AD 비중","약 60–70%","WHO","2021",false]],
      body: [["질환과 증후군의 분리",["AD — 원인 질환의 생물학적 연속체","dementia — 기억·사고·행동·일상 기능 저하의 임상 증후군","AD 없는 dementia와 dementia 전 AD 병리 모두 존재"]],["해석의 기준",["증상 중심 probable AD → biomarker 기반 질환 정의로 이동","혼합병리 → 임상 증후군과 단일 원인 병리의 일대일 대응 경계","역학 수치의 AD 단독·all-cause dementia 분모 분리"]]],
      related: ["ckd-stages","ckd-subtypes","ckd-criteria"], papers: [P.criteria,P.scheltens] },
    { id: "ckd-stages", section: "def", title: "임상·생물학적 단계는 어떻게 나누는가?",
      aliases: ["preclinical AD","MCI","mild dementia","staging","ATN"],
      summary: "생물학적 병기와 임상 병기는 평행하되 동일하지 않은 두 축 — 무증상 병리·MCI·치매 단계의 구분",
      facts: [["생물학적 틀","A/T/N biomarker 분류","NIA-AA Research Framework","2018",false],["최신 기준","진단·병기 revised criteria","Alzheimer's Association","2024",false],["치료시험 초기 AD","MCI 또는 mild dementia + amyloid 확인","CLARITY AD","2023",false]],
      body: [["두 개의 병기축",["생물학적 병기 — amyloid·tau·신경퇴행 biomarker","임상 병기 — 인지 정상·MCI·경증·중등도·중증 치매","같은 biomarker 단계에서도 서로 다른 임상 기능"]],["사용 맥락",["연구·치료선별 — 생물학적 확인의 비중 확대","돌봄 계획 — 일상 기능과 행동 증상의 임상 병기 중심","biomarker 양성만으로 증상 시점 단정 금지"]]],
      related: ["ckd-definition","ckd-preclinical","ckd-antiamyloid-eligibility"], papers: [P.criteria,P.scheltens] },
    { id: "ckd-subtypes", section: "def", title: "주요 아형과 감별 질환은 무엇인가?",
      aliases: ["early-onset","late-onset","familial Alzheimer","sporadic AD","mixed dementia"],
      summary: "조기 가족성 AD의 희귀 고침투 변이와 후기 AD의 APOE 중심 다유전자 구조 — 혼합병리와 비전형 임상형 동반",
      facts: [["조기 가족성 축","APP · PSEN1 · PSEN2","Scheltens et al.","2021",false],["후기 발병 축","APOE + 다수 common variant","Bellenguez et al.","2022",false],["감별 축","vascular · Lewy body · frontotemporal · 혼합병리","Scheltens et al.","2021",false]],
      body: [["유전 구조 기반 아형",["상염색체 우성 가족성 AD — 희귀·고침투 변이 중심","후기 발병 AD — APOE와 다수 작은 효과 변이의 합","발병 연령만으로 monogenic 여부 단정 금지"]],["임상·병리 기반 감별",["기억 우세 전형형과 언어·시공간 우세 비전형형","vascular·Lewy body·frontotemporal pathology와의 감별","고령층 혼합병리 → 단일 라벨의 한계"]]],
      related: ["ckd-apoe-rare","ckd-differential","ckd-heterogeneity"], papers: [P.scheltens,P.bellenguez] },
    { id: "ckd-prevalence", section: "epi", title: "세계와 한국에서 얼마나 흔한가?",
      aliases: ["prevalence","유병률","GBD","NHIS","HIRA","Korea"],
      summary: "2020년 AD dementia 약 3,200만명 · 2019년 전체 치매 5,740만명 · 한국 2019년 AD 진료 인원 680,800명 — 사례 정의와 분모가 달라 혼용 금지",
      facts: [["전 세계 AD dementia","약 3,200만명","Gustavsson et al.","2020 추정",false],["전 세계 전체 치매","5,740만명 (95% UI 5,040만–6,510만)","GBD 2019 forecast analysis","2019",false],["한국 AD 진료 인원","680,800명","HIRA 주상병 청구자료","2019",false],["한국 NHIS AD 청구 유병률","15.75/1,000명 (40세 이상·연령표준화)","Baek et al.","2015",false]],
      body: [["전 세계 분모",["AD dementia 추정 — AD 원인 치매만 포함","GBD·WHO 전체 치매 — AD 외 원인 포함","AD 단독 3,200만명과 전체 치매 5,740만명의 혼용 금지"]],["한국 수치의 성격",["HIRA 680,800명 — 2019년 주상병 청구 진료 인원","NHIS 15.75/1,000명 — 40세 이상·F00/G30 + 항치매약의 조작적 정의","청구자료는 지역사회 유병률 아님 — 미진단·미수진·코딩 차이 포함"]]],
      related: ["ckd-trend","ckd-demographics","ckd-burden"], papers: [P.globalAD,P.gbdForecast,P.korea,P.koreaHira], links: [["WHO dementia fact sheet","https://www.who.int/news-room/fact-sheets/detail/dementia"]] },
    { id: "ckd-trend", section: "epi", title: "환자 수와 발생은 어떻게 변하는가?",
      aliases: ["incidence","trend","forecast","2050","발생률","추세"],
      summary: "전체 치매 환자 2019년 5,740만명 → 2050년 1억5,280만명 전망 · 한국 AD 청구 발생률 2006년 1.83 → 2015년 5.21/1,000명",
      facts: [["세계 전체 치매 전망","5,740만명 → 1억5,280만명","GBD 2019 forecast analysis","2019→2050",false],["세계 연령표준화 유병률 변화","+0.1% (95% UI −7.5~10.8)","GBD 2019 forecast analysis","2019→2050",false],["한국 AD 청구 발생률","1.83 → 5.21/1,000명 (40세 이상·연령표준화)","Baek et al.","2006→2015",false]],
      body: [["절대 수와 표준화율",["절대 환자 수 급증 전망 — 인구 증가와 고령화의 영향","연령표준화 유병률은 거의 안정 전망","환자 수 증가를 개인별 위험 증가로 해석 금지"]],["한국 추세의 해석",["청구 발생 인원 30,439명 → 122,580명","2008년 국가 치매계획·조기검진 확대와 시기 중첩","실제 발생 변화와 진단·청구 포착 증가의 분리 필요"]]],
      related: ["ckd-prevalence","ckd-demographics","ckd-burden"], papers: [P.gbdForecast,P.korea] },
    { id: "ckd-demographics", section: "epi", title: "연령·성별·지역별 차이는 무엇인가?",
      aliases: ["age","sex","region","women","연령","성별"],
      summary: "연령에 따른 급격한 증가와 여성의 더 큰 사망·장애 부담 — 국가 간 차이는 인구구조·진단 접근·사례확인의 영향",
      facts: [["한국 65–69세 청구 유병률","13.2/1,000명","Baek et al.","2015",false],["한국 85–89세 청구 유병률","204.97/1,000명","Baek et al.","2015",false],["치매 사망 여성 비중","약 65%","WHO Global Dementia Observatory","2019",false]],
      body: [["연령과 성별",["연령 — 가장 강한 인구학적 축","여성의 더 큰 환자 수·DALY·사망 부담 — 수명과 표준화 차이 분리","한국 65–69세와 85–89세 청구 유병률 약 15.5배 차이"]],["지역 차이",["의료 접근·진단 기준·사망 코딩의 국가별 차이","저·중소득국의 큰 미진단 부담 가능성","동일 연령대·사례 정의 없는 국가 간 직접 비교 금지"]]],
      related: ["ckd-prevalence","ckd-trend","ckd-ancestry-family"], papers: [P.korea,P.gbdForecast], links: [["WHO Global Dementia Observatory","https://www.who.int/data/gho/data/themes/global-dementia-observatory-gdo"]] },
    { id: "ckd-burden", section: "epi", title: "질병부담과 돌봄 비용은 얼마나 큰가?",
      aliases: ["DALY","mortality","cost","caregiver","질병부담","돌봄"],
      summary: "전체 치매 2016년 2,880만 DALY · 2019년 사망 162만명 · 사회적 비용 US$1.3조 — AD 단독 부담으로 오인 금지",
      facts: [["전체 치매 DALY","2,880만 (95% UI 2,450만–3,400만)","GBD 2016 Dementia Collaborators","2016",false],["전체 치매 사망","162만명 (95% UI 41만–421만)","GBD 2019 mortality analysis","2019",false],["세계 사회적 비용","US$1.3조","WHO Global Status Report","2019",false],["비공식 돌봄 비중","전체 비용의 약 50%","WHO","2019",false]],
      body: [["부담의 구성",["인지·기능 상실 → 장기 돌봄·보호자 시간·의료 이용","직접 의료비보다 큰 사회·비공식 돌봄 비용","말기 pneumonia·dysphagia·bedridden 상태와 사망 부담"]],["수치 해석",["GBD·WHO 값은 Alzheimer's disease and other dementias 또는 전체 치매","AD 단독 DALY·사망·비용으로 그대로 전환 금지","한국 AD 단독 돌봄·생산성 비용 — 직접 조사 대상"]]],
      related: ["ckd-prevalence","ckd-trend","ckd-unmet"], papers: [P.gbdBurden], links: [["WHO Global Status Report on Dementia","https://www.who.int/publications/i/item/9789240033245"]] },
    { id: "ckd-heritability", section: "risk", title: "유전 위험은 얼마나 큰가?",
      aliases: ["heritability","유전율","polygenic","missing heritability"],
      summary: "AD 유전율 약 60–80% · APOE의 큰 효과와 75개 GWAS loci의 작은 효과가 공존하는 다유전자 구조",
      facts: [["유전율","약 60–80%","Scheltens et al.","2021",false],["GWAS loci","75개 · 42개 신규","Bellenguez et al.","2022",false],["GWAS 표본","111,326 AD/proxy + 677,663 대조","Bellenguez et al.","2022",false]],
      body: [["유전 구조",["희귀 고침투 변이 + common polygenic risk의 공존","APOE — 후기 발병 AD의 최강 단일 위험 인자","유전율과 현재 GWAS 설명분산 사이의 간극"]],["해석 경계",["유전율 — 집단 수준 분산 · 개인 운명 아님","proxy-AD 포함 → 표본 확대와 표현형 희석의 교환","유럽계 중심 추정치의 타 ancestry 직접 적용 제한"]]],
      related: ["ckd-apoe-rare","ckd-gwas","ckd-prs"], papers: [P.scheltens,P.bellenguez] },
    { id: "ckd-apoe-rare", section: "risk", title: "APOE와 희귀 고침투 변이는 어떻게 다른가?",
      aliases: ["APOE","APOE4","APP","PSEN1","PSEN2","protective variants"],
      summary: "APP·PSEN1·PSEN2는 희귀 가족성 AD의 고침투 축 · APOE는 후기 발병 위험의 최강 common 축 · 보호 변이는 기전 단서",
      facts: [["common 최대효과","APOE","Scheltens et al.","2021",false],["가족성 고침투 유전자","APP · PSEN1 · PSEN2","Scheltens et al.","2021",false],["보호 변이 후보","APOE ε2 · APP Ala673Thr · PLCG2 P522R · APOE Christchurch","AD synthesis","2021–2022",false]],
      body: [["서로 다른 위험 모델",["APP·PSEN — amyloid 생성 경로의 희귀 고침투 변이","APOE — 지질 운반·amyloid 처리·microglia 상태와 연결된 common 위험","APOE genotype만으로 발병 확정 또는 배제 금지"]],["보호 변이의 의미",["위험 유전자와 같은 경로의 반대 방향 자연 실험","amyloid·면역·지질 처리의 치료 표적 단서","희귀 보호효과의 일반 인구 치료 전환은 초기 단계"]]],
      related: ["ckd-heritability","ckd-neuroimmune-course","ckd-aria"], papers: [P.scheltens,P.bellenguez] },
    { id: "ckd-nongenetic-risk", section: "risk", title: "비유전 위험·보호요인은 무엇인가?",
      aliases: ["aging","vascular risk","diabetes","hypertension","lifestyle","risk factor"],
      summary: "노화가 최강 비유전 축 · 혈관 위험은 AD와 동반되지만 amyloid/tau 비매개 경로 가능성 — 연관과 기전의 분리",
      facts: [["한국 diabetes 동반군 AD 청구 발생률","6.48/1,000명 vs 비동반 4.93/1,000명","Baek et al.","2015",false],["한국 hypertension 동반군","5.34/1,000명 vs 비동반 5.24/1,000명","Baek et al.","2015",false],["핵심 비유전 축","노화 · 혈관 위험","Scheltens et al.","2021",false]],
      body: [["위험 축",["노화 — 유병률 곡선을 지배하는 배경","당뇨·고혈압·지질·뇌혈관 손상 — 관찰·청구 연관","생활·환경 요인 — 노출 시기와 누적 부담의 영향"]],["해석의 경계",["청구자료 연관 → 인과효과 아님","혈관 위험의 amyloid/tau 비매개 기여 가능성","혈관-amyloid 상호작용 보고와의 잠재적 불일치"]]],
      related: ["ckd-ancestry-family","ckd-atn-course","ckd-vascular-microglia"], papers: [P.scheltens,P.korea] },
    { id: "ckd-ancestry-family", section: "risk", title: "ancestry와 가족력은 위험 해석을 어떻게 바꾸는가?",
      aliases: ["ancestry","family history","European","transferability","가족력"],
      summary: "가족력은 희귀 고침투 변이와 common polygenic burden을 함께 반영 · European 기반 GRS의 비유럽 전이성 제한",
      facts: [["Bellenguez GRS ancestry","European 전용","Bellenguez et al.","2022",false],["한국인 PRS 보정 성능","확인 필요 — 한국인 독립 코호트 직접 분석","직접 분석 필요","",true],["가족성 유전자","APP · PSEN1 · PSEN2","Scheltens et al.","2021",false]],
      body: [["가족력의 층위",["다세대 조기 발병 집적 → monogenic 원인 우선 검토","후기 발병 가족력 → APOE·polygenic burden·공유환경의 합","가족력 부재만으로 유전 위험 배제 금지"]],["ancestry 전이성",["대립유전자 빈도·LD·환경 배경의 집단 차이","European effect size를 한국인 개인예측에 무보정 사용 금지","동일 정의·외부 코호트의 calibration과 discrimination 검증 필요"]]],
      related: ["ckd-heritability","ckd-prs","ckd-transferability"], papers: [P.bellenguez,P.scheltens] },
    { id: "ckd-preclinical", section: "course", title: "병리 변화는 증상보다 얼마나 먼저 시작되는가?",
      aliases: ["preclinical","biomarker trajectory","asymptomatic","무증상"],
      summary: "amyloid biomarker 양성은 임상 dementia보다 약 15년 앞선 집단 패턴 — 개인별 발병 시계로 사용 금지",
      facts: [["병리 선행","임상 AD 유병 곡선보다 amyloid 양성 곡선 약 15년 선행","NIA-AA Research Framework","2018",false],["preclinical AD 추정","약 3억1,500만명","Gustavsson et al.","2020 추정",false],["prodromal AD 추정","약 6,900만명","Gustavsson et al.","2020 추정",false]],
      body: [["무증상 구간",["amyloid 축적 → 수년 이상의 무증상 생물학적 단계","tau·신경퇴행의 추가 → 임상 발현 가능성 상승","biomarker 양성과 필연적 dementia의 구분"]],["수치의 한계",["3억1,500만·6,900만명 — 모델 기반 AD continuum 추정","전체 치매 환자 수와 다른 사례 정의","개인별 전환 시점·평생 위험의 직접 추정 불가"]]],
      related: ["ckd-stages","ckd-atn-course","ckd-biomarkers"], papers: [P.globalAD,P.criteria] },
    { id: "ckd-atn-course", section: "course", title: "amyloid·tau·신경퇴행은 어떤 순서로 진행하는가?",
      aliases: ["amyloid","tau","neurodegeneration","ATN","cascade"],
      summary: "A/T/N은 병리 종류를 분리하는 좌표계 · amyloid 제거와 임상효과의 크기 불일치로 단순 직선형 cascade 해석 제한",
      facts: [["A","amyloid pathology biomarker","NIA-AA","2018",false],["T","pathologic tau biomarker","NIA-AA","2018",false],["N","neurodegeneration·neuronal injury biomarker","NIA-AA","2018",false]],
      body: [["진행 좌표",["amyloid 축적 → tau 확산·신경퇴행 위험의 배경","tau burden과 임상 기능의 더 가까운 대응","세 축의 시간차·비선형성·환자 간 차이"]],["단순화의 위험",["amyloid 유전 근거는 강함","amyloid plaque 감소와 인지 이득의 크기는 불일치","biomarker 변화 ≠ 동일 크기의 임상 효과"]]],
      related: ["ckd-preclinical","ckd-treatment-effect","ckd-biomarkers"], papers: [P.scheltens,P.criteria,P.lecanemab,P.donanemab] },
    { id: "ckd-neuroimmune-course", section: "course", title: "microglia·혈관·경계 면역은 진행에 어떻게 관여하는가?",
      aliases: ["microglia","TREM2","APOE","endothelial","meningeal lymphatic","neuroimmune","glymphatic","AQP4","CSF clearance","수막"],
      summary: "AD 유전 위험의 microglia 수렴 + endothelial loss·뇌 경계 배수 축 — amyloid·tau만으로 설명되지 않는 cellular phase",
      facts: [["microglia enrichment","P=1.7×10⁻⁸","Bellenguez et al.","2022",false],["혈관 조성","AD에서 endothelial cell proportion 감소","Yap et al.","2024",false],["경계 면역","meningeal lymphatic 노화와 amyloid 제거 저하","Rustenhoven et al.","2023",false],["수막 기질","노화 dura의 peri-lymphatic type I collagen 축적 → 수막 림프 배수 저하","Hitpass Romero et al.","2025",false],["청소 구동력","40 Hz 다감각 자극 → 동맥 pulsatility·AQP4 극성화 → amyloid 제거 증가","Murdock et al.","2024",false]],
      body: [["세포·경계 축",["APOE·TREM2·PLCG2·ABCA7 → microglia·면역 기능으로 수렴","endothelial loss와 neurovascular unit 변화","수막 림프 노화 → CSF 배수 저하 — dural fibroblast의 TGFβ 신호·기질 강성이 기전 후보","뉴런 활동 → 동맥 박동 → CSF-ISF 교환 — amyloid 제거의 유체 경로"]],["측정 단위의 분리",["CSF 유입 · 실질 내 교환 · 용질 유출 · 수막 림프 배출 — 단계별로 다른 tracer·시간척도","구동력 구분 — 심박 pulsatility · 느린 vasomotion · 뇌실막 섬모","AQP4 — 총량이 아닌 astrocyte endfoot 배치(극성화)가 지표"]],["인과성 경계",["microglia activation — 보호적 제거와 병원성 염증의 양면","endothelial 변화 — methylation deconvolution·PGS 기반 추론","배수 경로 인과는 mouse 개입 근거 — 인간 배수 정량 표준 부재","인간 종단·기능 검증 전 치료 인과 단정 금지"]]],
      related: ["ckd-apoe-rare","ckd-variant-celltype","ckd-vascular-microglia"], papers: [P.bellenguez,P.yap,P.romero,P.murdock] },
    { id: "ckd-heterogeneity", section: "course", title: "진행 속도와 회복탄력성은 왜 다른가?",
      aliases: ["heterogeneity","resilience","resistance","progression","인지 예비력"],
      summary: "같은 진단 안의 유전 배경·혼합병리·세포 상태·혈관 부담 차이 → biomarker와 임상 진행의 비동기",
      facts: [["cell-type 반응","APOE 발현 방향이 microglia↑ · astrocyte↓","Mathys et al.","2019",false],["다영역 atlas","6개 뇌영역 single-cell 분석","Mathys et al.","2024",false],["임상 예측","개인별 진행 속도의 정밀 예측치 미확립","AD synthesis","2026",false]],
      body: [["이질성의 원천",["APOE·polygenic background·희귀 변이의 조합","amyloid·tau·혈관·Lewy body 등 혼합병리","뇌영역·세포유형별 취약성과 반응의 차이"]],["연구 설계",["횡단 사례-대조보다 종단 biomarker·인지 추적","임상 진행자와 resilience·resistance 집단의 분리","예측모델의 외부 코호트 calibration 필수"]]],
      related: ["ckd-subtypes","ckd-singlecell","ckd-unmet"], papers: [P.mathys,P.mathys2024,P.scheltens] },
    { id: "ckd-symptoms", section: "dx", title: "초기 증상과 경고 신호는 무엇인가?",
      aliases: ["memory loss","MCI","early symptoms","episodic memory","초기 증상"],
      summary: "새로운 episodic memory 저하와 복합 일상 기능의 변화가 전형적 출발점 · 언어·시공간 우세 비전형 표현형도 존재",
      facts: [["전형적 초기축","episodic memory 저하","Scheltens et al.","2021",false],["prodromal 임상단계","MCI due to AD","NIA-AA","2011–2024",false],["비전형축","언어 · 시공간 · 실행기능 우세","Scheltens et al.","2021",false]],
      body: [["전형적 신호",["최근 사건·대화의 반복적 망각","약 복용·재정·길찾기 등 복합 일상 기능의 변화","정상 노화와 구분되는 지속·진행·기능 영향"]],["비전형과 주의",["언어·시공간·실행기능 우세 presentation","우울·수면·약물·감각저하와의 증상 중첩","증상만으로 AD 병리 확정 금지"]]],
      related: ["ckd-criteria","ckd-biomarkers","ckd-differential"], papers: [P.scheltens,P.criteria] },
    { id: "ckd-criteria", section: "dx", title: "최신 진단 기준은 무엇인가?",
      aliases: ["2024 revised criteria","Core 1 biomarker","diagnostic criteria","DETeCD-ADRD"],
      summary: "2024 Alzheimer's Association revised criteria — 비정상 Core 1 biomarker를 AD 진단의 생물학적 근거로 사용 · 임상 병기는 별도 평가",
      facts: [["최신 질환 기준","Revised criteria for diagnosis and staging of AD","Alzheimer's Association Workgroup","2024",false],["진단 원리","비정상 Core 1 biomarker","Jack et al.","2024",false],["전문진료 평가지침","DETeCD-ADRD executive summary","Alzheimer's Association","2024",false]],
      body: [["핵심 변화",["증후군 중심 probable AD → 생물학적 질환 정의","Core 1 biomarker 이상 → AD 병리의 진단 근거","생물학적 병기와 임상 기능 병기의 분리"]],["적용 주의",["무증상 인구검진과 증상 환자 진료의 맥락 구분","검사 성능·사전확률·혼합병리의 동시 고려","연구기준·임상지침·규제 치료 적격 기준의 구분"]]],
      related: ["ckd-stages","ckd-biomarkers","ckd-guideline-change"], papers: [P.criteria], links: [["Alzheimer's Association DETeCD-ADRD overview","https://www.alz.org/news/2024/clinical-practice-guideline-evaluation-alzheimers"]] },
    { id: "ckd-biomarkers", section: "dx", title: "혈액·CSF·PET·MRI 바이오마커를 어떻게 조합하는가?",
      aliases: ["p-tau217","p-tau181","Aβ42/40","NfL","amyloid PET","tau PET","MRI"],
      summary: "혈액 p-tau181/217·Aβ42/40로 접근성 확대 → CSF·PET로 병리 확인 · MRI로 신경퇴행·혈관병리·치료 안전성 평가",
      facts: [["혈액 후보","p-tau181/217 · Aβ42/40 · NfL","Scheltens et al.","2021",false],["병리 영상","amyloid PET · tau PET","Jack et al.","2024",false],["구조·안전 영상","MRI","Jack et al. · anti-amyloid AUR","2023–2024",false]],
      body: [["검사 역할",["혈액 — 저침습 선별·triage","CSF·PET — amyloid·tau 병리의 확인","MRI — 위축·혈관성 병변·microbleed·ARIA 평가"]],["조합 원칙",["검사 하나보다 임상 사전확률과 다중 modality의 결합","cutoff·platform·검사실 간 표준화 확인","NfL은 신경퇴행 표지이나 AD 특이 표지 아님"]]],
      related: ["ckd-criteria","ckd-antiamyloid-eligibility","ckd-aria"], papers: [P.scheltens,P.criteria,P.lecanemabAur] },
    { id: "ckd-differential", section: "dx", title: "치매 아형과 가역적 원인을 어떻게 감별하는가?",
      aliases: ["differential diagnosis","vascular dementia","Lewy body","FTD","reversible causes"],
      summary: "임상표현형·진찰·약물·대사 평가·영상·병리 biomarker의 단계적 결합 → AD 단독·혼합·비AD 원인 분리",
      facts: [["주요 퇴행성 감별","Lewy body · frontotemporal","Scheltens et al.","2021",false],["혈관 감별","vascular cognitive impairment · 혼합병리","Scheltens et al.","2021",false],["가역·교정 가능 축","약물 · 대사 · 수면 · 우울 · 감각저하","DETeCD-ADRD","2024",false]],
      body: [["감별 순서",["발병 양상·인지 영역·기능 저하·행동 증상","신경학적 진찰·약물·전신질환·정신건강 평가","MRI와 선택적 CSF·PET·혈액 biomarker"]],["혼합병리",["고령층 AD와 vascular·Lewy body 병리의 동시 존재","한 원인의 확인이 다른 원인의 배제와 동일하지 않음","치료 가능 요인의 병행 교정"]]],
      related: ["ckd-subtypes","ckd-symptoms","ckd-biomarkers"], papers: [P.scheltens,P.criteria] },
    { id: "ckd-standard-care", section: "tx", title: "표준 증상 치료와 비약물 관리는 무엇인가?",
      aliases: ["donepezil","rivastigmine","galantamine","memantine","nonpharmacological"],
      summary: "AChE inhibitor·memantine의 modest symptomatic benefit + 기능·행동·보호자 지원 — 질병 제거와 구분",
      facts: [["memantine responder","29% vs placebo 10% (사전정의 composite)","Reisberg et al.","2003",false],["donepezil 26주 ADAS-Cog","평균차 −2.67점 (95% CI −3.31~−2.02)","Cochrane","2018",false],["NICE 관리지침","NG97 · 2018 발행 · 2025 검토","NICE","2018/2025",false]],
      body: [["약물 관리",["mild–moderate AD — donepezil·rivastigmine·galantamine","moderate–severe AD — memantine 단독 또는 병용 맥락","효과 — 평균적 증상·기능 저하의 modest 완화"]],["비약물·돌봄",["운동·인지·사회활동·환경 단순화","행동 증상의 유발요인 평가와 비약물 우선 접근","보호자 교육·안전·향후 의사결정 지원"]]],
      related: ["ckd-antiamyloid-eligibility","ckd-treatment-effect","ckd-unmet"], papers: [P.memantine,P.nice], links: [["Cochrane donepezil review","https://www.cochrane.org/evidence/CD001190_donepezil-people-dementia-due-alzheimers-disease"]] },
    { id: "ckd-antiamyloid-eligibility", section: "tx", title: "anti-amyloid 항체는 누구에게 적용하는가?",
      aliases: ["lecanemab eligibility","donanemab eligibility","amyloid positive","MCI","mild dementia"],
      summary: "MCI 또는 mild dementia due to AD + amyloid 병리 확인 + MRI 안전성 검토가 핵심 적격 틀",
      facts: [["lecanemab 시험 대상","50–90세 · MCI 또는 mild dementia · amyloid 양성","CLARITY AD","2023",false],["donanemab 시험 대상","early symptomatic AD · amyloid·tau PET 선별","TRAILBLAZER-ALZ 2","2023",false],["국내 lecanemab 허가","경도인지장애 또는 경증 AD dementia 성인","MFDS","2024",false]],
      body: [["적격 평가",["초기 임상 단계 확인","amyloid PET 또는 CSF 등 병리 확인","기저 MRI·APOE ε4·항응고제·출혈 위험 검토"]],["적용 제외·주의",["중등도·중증 시작의 효능·안전 근거 부족","광범위 microbleed·superficial siderosis 등 MRI 위험 소견","시험 포함집단 밖 환자에 대한 일반화 제한"]]],
      related: ["ckd-biomarkers","ckd-treatment-effect","ckd-aria"], papers: [P.lecanemab,P.donanemab,P.lecanemabAur] },
    { id: "ckd-treatment-effect", section: "tx", title: "lecanemab과 donanemab은 진행을 얼마나 늦추는가?",
      aliases: ["CLARITY AD","TRAILBLAZER-ALZ 2","CDR-SB","iADRS","efficacy"],
      summary: "lecanemab CDR-SB 저하 27% 감속 · donanemab iADRS 저하 22.3% 전체·35.1% low/medium tau 감속 — 서로 다른 척도·집단의 직접 비교 금지",
      facts: [["lecanemab","18개월 CDR-SB 1.21 vs 1.66 · 차이 −0.45 · 약 27% 감속","van Dyck et al., NEJM 388:9–21","2023",false],["donanemab 전체","76주 iADRS 저하 22.3% 감속 (95% CI 11.38–33.15)","Sims et al., JAMA 330:512–527","2023",false],["donanemab low/medium tau","76주 iADRS 저하 35.1% 감속 (95% CI 19.90–50.23)","Sims et al.","2023",false]],
      body: [["효과의 크기",["두 약제 모두 plaque 감소와 통계적 임상 저하 감속","질환 정지·회복이 아닌 평균 진행 속도의 완만한 감소","절대 척도 차이와 환자·보호자 체감의 동시 설명 필요"]],["비교 주의",["lecanemab — CDR-SB · donanemab — iADRS 주분석","tau 선별·투여 중단 규칙·시험집단 차이","27%와 35.1%의 약제 간 직접 우열 비교 금지"]]],
      related: ["ckd-antiamyloid-eligibility","ckd-aria","ckd-unmet"], papers: [P.lecanemab,P.donanemab] },
    { id: "ckd-aria", section: "tx", title: "ARIA와 치료 안전성을 어떻게 관리하는가?",
      aliases: ["ARIA-E","ARIA-H","microhemorrhage","APOE4","MRI monitoring"],
      summary: "lecanemab ARIA-E 12.6%·donanemab 24.0% — APOE ε4·출혈 위험과 반복 MRI를 포함한 benefit-risk 평가",
      facts: [["lecanemab ARIA-E","12.6% vs placebo 1.7% · ARIA-H 17.3% vs 9.0%","van Dyck et al.","2023",false],["donanemab ARIA-E","24.0% · symptomatic 6.1% · ARIA-H 31.4%","Sims et al.","2023",false],["donanemab ARIA 관련 사망","3명","Sims et al. · FDA review","2023–2024",false],["lecanemab 조기 MRI 추가","3번째 infusion 전 MRI","FDA safety communication","2025",false]],
      body: [["위험 평가",["ARIA-E — edema·effusion · ARIA-H — microhemorrhage·siderosis","APOE ε4 homozygote의 더 높은 ARIA 위험","항응고제·기저 microbleed·cerebral amyloid angiopathy 고려"]],["모니터링",["투여 전 MRI와 약제별 정기 MRI","두통·혼돈·시각·보행·국소신경 증상 시 즉시 평가","중증도에 따른 보류·중단·추적 MRI"]]],
      related: ["ckd-antiamyloid-eligibility","ckd-treatment-effect","ckd-drug-update"], papers: [P.lecanemab,P.donanemab,P.lecanemabAur,P.donanemabAur], links: [["FDA 2025 lecanemab MRI safety update","https://www.fda.gov/drugs/drug-safety-communications/fda-recommend-additional-earlier-mri-monitoring-patients-alzheimers-disease-taking-leqembi-lecanemab"]] },
    { id: "ckd-unmet", section: "tx", title: "치료반응과 접근성의 미충족 수요는 무엇인가?",
      aliases: ["unmet need","access","response prediction","long-term efficacy","infrastructure"],
      summary: "평균 효과는 modest · 개인 반응 예측·장기 임상효과·주입·MRI·biomarker 접근성의 동시 미충족",
      facts: [["단기 핵심 근거","18개월 또는 76주 phase 3","CLARITY AD · TRAILBLAZER-ALZ 2","2023",false],["한국 lecanemab 실사용 적격·접근 규모","확인 필요 — 전국 단위 처방·MRI·amyloid 확인 자료 조사","직접 조사 필요","",true],["개인 반응 예측 marker","임상 확립치 없음","AD synthesis","2026",false]],
      body: [["임상 미충족",["평균 상대 감속을 개인별 benefit으로 변환하는 예측도구 부족","중등도 이후 질병조절 치료 근거 공백","amyloid 제거 이후 장기 기능·생존 효과의 추가 추적"]],["시스템 미충족",["biomarker 확인·주입·반복 MRI·ARIA 대응 인프라","도시·지역과 소득에 따른 접근 격차","보호자 부담·공유의사결정·총비용 평가"]]],
      related: ["ckd-standard-care","ckd-treatment-effect","ckd-aria"], papers: [P.lecanemab,P.donanemab,P.scheltens] },
    { id: "ckd-gwas", section: "omics", title: "GWAS는 어떤 loci와 경로를 지목하는가?",
      aliases: ["GWAS","75 loci","TREM2","PLCG2","ABCA7","LUBAC"],
      summary: "Bellenguez 2022의 75 loci(42 신규) → amyloid·tau·endocytosis에 microglia·면역·TNF-α/LUBAC 축 추가",
      facts: [["유의 loci","75개 · 42개 신규 · P≤5×10⁻⁸","Bellenguez et al.","2022",false],["표본","111,326 AD/proxy + 677,663 대조","Bellenguez et al.","2022",false],["핵심 면역 유전자","TREM2 · PLCG2 · ABCA7","Bellenguez et al.","2022",false]],
      body: [["경로 수렴",["amyloid·tau·endocytosis의 기존 축","microglia·면역 활성화의 강화","TNF-α·LUBAC 관련 경로의 추가"]],["locus에서 기전까지",["연관 locus ≠ 인과변이·표적 유전자","fine-mapping·QTL·colocalization·기능 검증의 연쇄","proxy-AD와 ancestry 편중의 해석 제한"]]],
      related: ["ckd-heritability","ckd-prs","ckd-variant-celltype"], papers: [P.bellenguez] },
    { id: "ckd-prs", section: "omics", title: "APOE 외 polygenic risk는 무엇을 더하는가?",
      aliases: ["PRS","GRS","polygenic risk score","83 variants","MCI conversion"],
      summary: "APOE 외 83변이 GRS가 발병·MCI→AD 진행과 연관(HR 1.076/allele) · 예측 개선은 소폭이며 European 밖 보정 필요",
      facts: [["GRS 구성","APOE 외 83변이","Bellenguez et al.","2022",false],["발병·진행 연관","HR 1.076/allele · P=9.23×10⁻⁴⁰","Bellenguez et al.","2022",false],["한국인 외부검증","확인 필요 — 독립 한국인 코호트 calibration","직접 분석 필요","",true]],
      body: [["추가 정보",["APOE 단일 locus 밖의 누적 common-variant burden","발병과 MCI→AD progression의 통계적 층화","APOE와 독립적인 소폭 예측 개선"]],["임상 전제",["상대위험과 절대위험의 구분","연령·성별·가족력·biomarker 위의 증분 성능","European 모델의 한국인 적용 전 calibration·clinical utility 검증"]]],
      related: ["ckd-gwas","ckd-ancestry-family","ckd-transferability"], papers: [P.bellenguez] },
    { id: "ckd-variant-celltype", section: "omics", title: "위험변이는 어떤 세포에서 작동하는가?",
      aliases: ["microglia enrichment","caQTL","non-neuron","cell type","colocalization"],
      summary: "단일세포 발현 enrichment의 microglia 단독 유의 + cell-type caQTL의 non-neuron AD enrichment → 면역·비뉴런 작동세포 우선순위",
      facts: [["microglia enrichment","P=1.7×10⁻⁸","Bellenguez et al.","2022",false],["caQTL donor","616명","Zeng et al.","2024",false],["공유 caQTL","neuron/non-neuron 간 10.4%","Zeng et al.","2024",false]],
      body: [["세포 지목",["GWAS gene-set·single-cell expression enrichment → microglia","neuron/non-neuron caQTL 차이 → 강한 세포특이 조절","APOE·TREM2·PLCG2를 포함한 면역세포 경로"]],["검증 사다리",["fine-mapping → caQTL/eQTL → colocalization","MPRA·CRISPR·인간 세포 모델의 기능 확인","뇌영역·질병상태·ancestry별 재현"]]],
      related: ["ckd-gwas","ckd-singlecell","ckd-new-method"], papers: [P.bellenguez,P.zeng] },
    { id: "ckd-singlecell", section: "omics", title: "bulk와 single-cell 연구는 무엇을 보여주는가?",
      aliases: ["bulk","snRNA-seq","single-cell","cell fraction","atlas"],
      summary: "bulk의 세포조성 혼합을 single-cell이 분해 → APOE의 microglia↑·astrocyte↓ 같은 세포유형별 반대 반응과 영역별 취약성",
      facts: [["Mathys 2019","6개 주요 뇌세포 유형의 병리 연관 subpopulation","Mathys et al.","2019",false],["APOE 방향","microglia↑ · astrocyte↓","Mathys et al.","2019",false],["다영역 확장","6개 뇌영역 atlas","Mathys et al.","2024",false]],
      body: [["해상도 변화",["bulk 차이 — 세포분율과 세포내 발현의 혼합","single-cell/nucleus — cell type·state·region별 반응 분리","동일 유전자의 세포유형별 반대 방향"]],["해석의 한계",["사후뇌 횡단자료 → 원인·결과·말기 변화의 혼재","희귀 세포·손실 세포의 포착 편향","독립 cohort·종단·공간 검증 필요"]]],
      related: ["ckd-variant-celltype","ckd-vascular-microglia","ckd-new-data"], papers: [P.mathys,P.mathys2024] },
    { id: "ckd-vascular-microglia", section: "omics", title: "혈관·microglia 신호와 임상표현형을 어떻게 연결하는가?",
      aliases: ["endothelial loss","microglia state","methylation deconvolution","PGS mediation"],
      summary: "Yap 2024의 endothelial loss·PGS 연관과 microglia 유전 enrichment를 임상 진행에 연결하려면 종단 paired multi-omic·인과 검증 필요",
      facts: [["Yap 자료","1,270 postmortem brain methylome","Yap et al.","2024",false],["AD 분석","300 AD + 418 undiagnosed","Yap et al.","2024",false],["AD PGS→endothelial","b=−0.008 · SE=0.003 · P=7.0×10⁻³","Yap et al.","2024",false]],
      body: [["현재 연결",["AD diagnosis·PGS와 endothelial cell proportion 감소의 연관","GWAS·caQTL의 microglia/non-neuron enrichment","혈관·면역 축이 amyloid·tau 경로와 만나는 후보 구조"]],["필요한 검증",["생전 임상·혈액·영상과 사후뇌 multi-omic의 연결","치료 전후 종단 single-cell·spatial 자료","PGS mediation과 진정한 인과효과의 구분"]]],
      related: ["ckd-neuroimmune-course","ckd-singlecell","ckd-new-method"], papers: [P.yap,P.bellenguez,P.zeng] },
    { id: "ckd-guideline-change", section: "now", title: "진단 기준과 진료 권고는 최근 어떻게 바뀌었는가?",
      aliases: ["guideline","2018 ATN","2024 revised criteria","DETeCD-ADRD","NICE NG97"],
      summary: "2018 연구용 AT(N) → 2024 생물학적 진단·병기 revised criteria와 DETeCD-ADRD · NICE NG97은 2018판을 2025 검토",
      facts: [["NIA-AA AT(N)","연구 프레임워크","Jack et al.","2018",false],["AD revised criteria","진단·병기 기준","Alzheimer's Association","2024",false],["DETeCD-ADRD","전문진료 진단평가 지침","Alzheimer's Association","2024",false],["NICE NG97","2018 발행 · 2025-10-24 최종 검토","NICE","2018/2025",false]],
      body: [["최근 변화",["연구용 생물학 정의에서 임상 진단·병기 틀로 확장","혈액 biomarker와 anti-amyloid 치료 시대의 평가 경로 반영","임상 기능과 생물학적 병리의 이중 보고"]],["개정 추적",["NICE — 정기 고정주기보다 surveillance·review 기반","Alzheimer's Association 기준 — biomarker·치료 변화에 따른 비정기 개정","발행연도·검토일·국가별 허가·급여의 동시 확인"]]],
      related: ["ckd-criteria","ckd-drug-update","ckd-standard-care"], papers: [P.criteria,P.nice] },
    { id: "ckd-drug-update", section: "now", title: "새 치료제와 승인 현황은 무엇인가?",
      aliases: ["Leqembi","Kisunla","lecanemab","donanemab","approval"],
      summary: "lecanemab FDA 정식승인 2023·한국 허가 2024 · donanemab FDA 승인 2024·EU 승인 2025 — 국가별 대상·APOE 제한 차이",
      facts: [["lecanemab FDA","traditional approval 2023-07-06","FDA","2023",false],["lecanemab 한국","MFDS 허가 2024-05-24","MFDS","2024",false],["donanemab FDA","approval 2024-07-02","FDA","2024",false],["donanemab EU","marketing authorisation 2025-09-24 · ApoE4 0–1 copy","EMA","2025",false]],
      body: [["승인 지형",["lecanemab — 초기 AD·amyloid 확인 중심","donanemab — 초기 증상 AD·amyloid 확인 중심","국가별 APOE ε4·급여·접근 프로그램의 차이"]],["지속 갱신점",["허가 적응증·투여경로·MRI 일정의 사후 변경","실사용 ARIA·출혈·중단 자료","한국 급여·전국 처방량·지역 접근성"]]],
      related: ["ckd-guideline-change","ckd-antiamyloid-eligibility","ckd-aria"], papers: [P.lecanemab,P.donanemab], links: [["FDA lecanemab traditional approval","https://www.fda.gov/news-events/press-announcements/fda-converts-novel-alzheimers-disease-treatment-traditional-approval"],["FDA 2024 novel approvals","https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024"],["EMA Kisunla","https://www.ema.europa.eu/en/medicines/human/EPAR/kisunla"]] },
    { id: "ckd-new-data", section: "now", title: "새 코호트·아틀라스·QTL 자원은 무엇이 생겼는가?",
      aliases: ["EADB","brainSCOPE","PsychENCODE","single-cell atlas","cohort","QTL"],
      summary: "EADB 75-locus GWAS · population-scale brain scQTL/caQTL · 6영역 AD single-cell atlas의 결합",
      facts: [["EADB GWAS","75 loci","Bellenguez et al.","2022",false],["brain scQTL","388 brains · >1.4M scQTL","Emani et al.","2024",false],["cell-type caQTL","616 donors","Zeng et al.","2024",false],["AD 다영역 atlas","6 brain regions","Mathys et al.","2024",false],["한국 AD multi-omic 공개 코호트 규모","확인 필요 — 국내 DAC·바이오뱅크 직접 조사","직접 조사 필요","",true]],
      body: [["새 참조자원",["대규모 GWAS summary statistics","PFC 중심 population-scale scQTL·caQTL","AD 다영역 single-cell transcriptomic atlas"]],["결합의 조건",["질환·대조·뇌영역·ancestry metadata 정렬","summary statistics·원자료의 접근권 차이","한국 코호트와의 외부 재현·보정"]]],
      related: ["ckd-gwas","ckd-singlecell","ckd-new-method"], papers: [P.bellenguez,P.emani,P.zeng,P.mathys2024] },
    { id: "ckd-new-method", section: "now", title: "새로 쓸 수 있게 된 분석 기법은 무엇인가?",
      aliases: ["scQTL","caQTL","colocalization","deconvolution","spatial transcriptomics","MPRA"],
      summary: "scQTL·caQTL·colocalization·methylation deconvolution·spatial의 결합 → 위험변이에서 세포·조직 맥락까지 연결",
      facts: [["scQTL bulk 미검출","약 2/3","Emani et al.","2024",false],["caQTL 공유율","neuron/non-neuron 10.4%","Zeng et al.","2024",false],["methylation deconvolution","7 major brain cell types","Yap et al.","2024",false]],
      body: [["방법 사다리",["fine-mapping·colocalization → 인과변이·표적 유전자 후보","scQTL·caQTL → 세포유형별 조절효과","single-cell·spatial·deconvolution → 조직 위치·조성·state"]],["검증 주의",["참조 atlas·뇌영역·ancestry 의존성","deconvolution의 rare cell 정확도와 조성-상태 혼동","MPRA·예측모델 결과의 내인성 기능 검증"]]],
      related: ["ckd-variant-celltype","ckd-vascular-microglia","ckd-transferability"], papers: [P.emani,P.zeng,P.yap] },
    { id: "ckd-transferability", section: "now", title: "인간·마우스·ancestry 전이성은 어떻게 검증하는가?",
      aliases: ["translation","mouse model","DAM","cross-ancestry","external validation"],
      summary: "마우스 DAM의 인간 부분 중첩 + European GRS 편중 → 인간 조직·다인종·독립 코호트의 단계적 재현 필수",
      facts: [["인간–마우스 microglia","부분 중첩 · C1QB·CD14 등 불일치","Mathys et al.","2019",false],["Bellenguez GRS","European 전용","Bellenguez et al.","2022",false],["한국인 AD PRS 전이성","확인 필요 — 직접 외부검증","직접 분석 필요","",true]],
      body: [["종간 전이",["마우스 DAM·tau 염증 신호의 인간 부분 일치","인간 사후뇌·iPSC·organoid·기능 perturbation의 삼각검증","종 보존 신호와 인간 특이 신호의 분리"]],["집단 전이",["European GWAS·QTL·atlas 편중","비유럽 ancestry의 LD·대립유전자 빈도·환경 맥락","한국인 독립 cohort의 calibration·discrimination·clinical utility"]]],
      related: ["ckd-ancestry-family","ckd-prs","ckd-new-method"], papers: [P.mathys,P.bellenguez,P.zeng] }
  ];

  const glossaryTerms = {
    "amyloid": { key: "amyloid", definition: "Amyloid-β. AD에서 plaque를 이루는 단백질 조각·생물학적 진단과 항체치료의 핵심 표적." },
    "tau": { key: "tau", definition: "신경세포 내 비정상 인산화와 tangle을 이루는 단백질·병기와 임상 진행에 가까운 표지." },
    "atn": { key: "atn", definition: "Amyloid(A)·pathologic tau(T)·neurodegeneration(N)을 분리해 표시하는 biomarker 분류." },
    "apoe": { key: "apoe", definition: "Apolipoprotein E. 후기 발병 AD의 최강 common 유전 위험 locus이자 ARIA 위험 평가 변수." },
    "microglia": { key: "microglia", definition: "뇌 상주 면역세포. AD GWAS 위험이 강하게 수렴하는 세포유형." },
    "trem2": { key: "trem2", definition: "Microglia 기능과 연결된 AD 위험 유전자." },
    "mci": { key: "mci", definition: "Mild cognitive impairment. 인지 저하가 있으나 독립적 일상 기능이 비교적 유지되는 임상 단계." },
    "p-tau217": { key: "ptau217", definition: "혈액·CSF에서 측정하는 phosphorylated tau biomarker 후보." },
    "aria": { key: "aria", definition: "Amyloid-related imaging abnormalities. 항amyloid 항체와 연관된 edema/effusion(ARIA-E) 또는 hemorrhage(ARIA-H) 영상 이상." },
    "prs": { key: "prs", definition: "Polygenic risk score. 다수 위험변이 효과를 합산한 유전 위험 점수." },
    "caqtl": { key: "caqtl", definition: "Chromatin accessibility QTL. 유전변이가 세포유형별 염색질 접근성에 미치는 효과." },
    "colocalization": { key: "coloc", definition: "GWAS와 QTL 신호가 같은 인과변이를 공유하는지 평가하는 통계 방법." }
  };
  const glossaryPattern = /(^|[^A-Za-z0-9가-힣])(amyloid|tau|ATN|APOE|microglia|TREM2|MCI|p-tau217|ARIA|PRS|caQTL|colocalization)(?=$|[^A-Za-z0-9])/gi;
  return { meta: meta, acts: acts, sections: sections, articles: articleList, glossaryTerms: glossaryTerms, glossaryPattern: glossaryPattern };
})();
