window.DISEASE = (function () {
  const meta = { id:"pd", title: "Parkinson's Disease (PD)", domain: "Neuro" };
  const acts = [
    { id:"A", num:"01", en:"DEFINITION · EPIDEMIOLOGY", title:"무엇인가", accent:"#6f3a55", blurb:"임상·병리 정의 · 아형·증상 스펙트럼 · 세계와 한국의 규모 · 질병부담", sections:["def","epi"] },
    { id:"B", num:"02", en:"RISK · COURSE", title:"왜·어떻게", accent:"#315d78", blurb:"희귀·흔한 유전위험 · 환경·보호요인 · 전구기 · α-synuclein·회로·인지 진행", sections:["risk","course"] },
    { id:"C", num:"03", en:"DIAGNOSIS · TREATMENT", title:"임상", accent:"#94553b", blurb:"초기 증상 · MDS 기준 · SAA·영상 · 도파민 치료 · DBS · 비운동 증상", sections:["dx","tx"] },
    { id:"D", num:"04", en:"GENETICS · RESEARCH", title:"연구", accent:"#1f5d43", blurb:"GWAS·희귀변이·ancestry · 세포유형·multi-omics · 기준·치료·데이터·방법 갱신", sections:["omics","now"] }
  ];
  const sections = {
    def: { number:"01", title:"정의 · 분류", act:"A", questions:[
      { q:"어떻게 정의하고 분류하는가?", note:"임상 parkinsonism · 흑질 도파민 신경 소실 · Lewy 병리", article: "ckd-definition" },
      { q:"파킨슨증후군·비전형 질환과 무엇이 다른가?", note:"원인질환 PD · 임상증후군 parkinsonism 분리", article: "ckd-differential" },
      { q:"주요 임상·생물학적 아형은 무엇인가?", note:"tremor/PIGD · brain-first/body-first · 유전성 층화", article: "ckd-subtypes" },
      { q:"운동·비운동 증상은 어떤 스펙트럼을 이루는가?", note:"운동축 · 자율신경·수면·기분·인지축", article: "ckd-symptom-spectrum" }
    ]},
    epi: { number:"02", title:"역학 · 질병부담", act:"A", questions:[
      { q:"세계와 한국에서 얼마나 흔한가?", note:"GBD 모형 · 임상문헌 · 한국 청구 진료 인원 분리", article: "ckd-prevalence" },
      { q:"발생률·유병률과 미래 부담은 어떻게 변하는가?", note:"2021 기준 · 한국 장기 추세 · 2050 전망", article: "ckd-trend" },
      { q:"어떤 연령·성별·집단에서 많이 발생하는가?", note:"고령 급증 · 남성 우세의 세계 추계 · 한국 여성 진료인원", article: "ckd-demographics" },
      { q:"장애·사망·돌봄 부담은 얼마나 큰가?", note:"DALY·사망 · 의료비 · 가족 돌봄", article: "ckd-burden" }
    ]},
    risk: { number:"01", title:"원인 · 위험인자", act:"B", questions:[
      { q:"주요 위험인자는 무엇인가?", note:"노화 · 환경·대사 노출 · 연관과 인과의 분리", article: "ckd-riskfactors" },
      { q:"희귀 고침투 변이와 흔한 변이는 각각 얼마나 기여하는가?", note:"monogenic 5–10% · 20+ 유전자 · common polygenic risk", article: "ckd-genetics" },
      { q:"보호요인과 촉발요인은 무엇인가?", note:"관찰연구 신호 · 역인과·교란 · 예방권고의 경계", article: "ckd-protective-triggers" },
      { q:"ancestry에 따라 위험변이 스펙트럼은 어떻게 다른가?", note:"유럽계·다인종 GWAS · African/African admixed 희귀변이", article: "ckd-ancestry-risk" }
    ]},
    course: { number:"02", title:"발병 · 진행", act:"B", questions:[
      { q:"운동증상 전에는 어떤 변화가 일어나는가?", note:"후각·REM수면행동·자율신경 · prodromal probability", article: "ckd-prodromal" },
      { q:"도파민 신경 소실과 α-synuclein 병리는 어떻게 진행되는가?", note:"흑질–선조체 회로 · Lewy 병리 · 전파모형의 경계", article: "ckd-progression" },
      { q:"환자마다 진행속도와 표현형이 다른 이유는 무엇인가?", note:"유전·병리·회로·보상능의 다층 이질성", article: "ckd-heterogeneity" },
      { q:"인지장애와 주요 합병증은 어떻게 전개되는가?", note:"SCD→PD-MCI→PDD · 운동변동·낙상·연하·정신증", article: "ckd-complications" }
    ]},
    dx: { number:"01", title:"진단 · 분류", act:"C", questions:[
      { q:"초기 증상은 무엇인가?", note:"bradykinesia·rigidity·rest tremor · 비운동 전구신호", article: "ckd-early-symptoms" },
      { q:"현재 임상 진단 기준은 무엇인가?", note:"MDS 2015 · established/probable · exclusion·red flag·supportive", article: "ckd-clinical-criteria" },
      { q:"어떤 검사와 바이오마커를 사용하는가?", note:"임상진찰 · MRI·DaT-SPECT · CSF/피부 α-syn SAA", article: "ckd-tests" },
      { q:"감별진단의 핵심 장벽은 무엇인가?", note:"초기 중첩 · 치료반응의 비특이성 · pathology 부재", article: "ckd-dx-differential" },
      { q:"생물학적 정의 프레임워크는 무엇이 다른가?", note:"NSD-ISS와 SynNeurGe · SAA 공통축 · 유전 기준 차이", article: "ckd-biological-definition" }
    ]},
    tx: { number:"02", title:"치료 · 미충족 수요", act:"C", questions:[
      { q:"현재 표준 약물치료는 무엇인가?", note:"levodopa · dopamine agonist · MAO-B/COMT inhibitor", article: "ckd-standard-tx" },
      { q:"운동 합병증과 DBS는 어떻게 관리하는가?", note:"wearing-off·dyskinesia · 약물조정·주입·DBS", article: "ckd-fluctuation-dbs" },
      { q:"인지·비운동 증상은 어떻게 치료하는가?", note:"rivastigmine · 정신증·수면·자율신경 · 재활", article: "ckd-nonmotor-tx" },
      { q:"치료반응과 부작용은 어떻게 균형 잡는가?", note:"운동효과 · dyskinesia · impulse control·환각·졸림", article: "ckd-response-safety" },
      { q:"질병 진행을 늦추는 치료는 어디까지 왔는가?", note:"증상개선과 disease modification 분리 · GLP-1·α-syn 시험", article: "ckd-unmet" }
    ]},
    omics: { number:"01", title:"유전학 · 오믹스", act:"D", questions:[
      { q:"GWAS는 어떤 유전자와 경로를 지목하는가?", note:"90 signal·78 region · lysosome·vesicle·면역", article: "ckd-gwas" },
      { q:"희귀변이·CNV·STR은 무엇을 더 보여주는가?", note:"GBA1·LRRK2·PRKN · African/African admixed 확장 분석", article: "ckd-rare-variants" },
      { q:"위험변이는 어떤 세포·조직에서 작동하는가?", note:"뇌·신경세포 enrichment · eQTL·methylation MR", article: "ckd-variant-celltype" },
      { q:"multi-omics와 single-cell 연구는 무엇을 보여주는가?", note:"locus→gene→cell state · 세포조성·ancestry 한계", article: "ckd-multiomics" }
    ]},
    now: { number:"02", title:"최신 동향", act:"D", questions:[
      { q:"진료 권고는 최근 어떻게 바뀌었는가?", note:"NICE NG71·AAN 2021 · 생물학 기준의 연구용 경계", article: "ckd-guideline-change" },
      { q:"새 치료제와 안전성 정보는 무엇인가?", note:"lixisenatide·prasinezumab·exenatide · 확증과 우려표시", article: "ckd-drug-update" },
      { q:"새 코호트·오믹스 데이터는 무엇이 생겼는가?", note:"multi-ancestry GWAS · African rare variant · 한국 BRIDGE", article: "ckd-new-data" },
      { q:"새로 쓸 수 있게 된 분석 기법은 무엇인가?", note:"SAA · long-read·joint calling · cell-type QTL·spatial", article: "ckd-new-method" }
    ]}
  };
  const P = {
    poewe:["Poewe et al. 2017, Nat Rev Dis Primers 3:17013","https://doi.org/10.1038/nrdp.2017.13"],
    gbd:["Yang et al. 2026, J Neurol Sci 480:125703","https://doi.org/10.1016/j.jns.2025.125703"],
    forecast:["Su et al. 2025, BMJ 388:e080952","https://doi.org/10.1136/bmj-2024-080952"],
    han:["Han et al. 2019, BMC Public Health 19:1328","https://doi.org/10.1186/s12889-019-7664-6"],
    koreaTrend:["Lee et al. 2026, npj Parkinsons Dis","https://doi.org/10.1038/s41531-026-01395-8"],
    mds:["Postuma et al. 2015, Mov Disord 30:1591–1601","https://doi.org/10.1002/mds.26424"],
    nsd:["Simuni et al. 2024, Lancet Neurol 23:178–190","https://doi.org/10.1016/S1474-4422(23)00405-2"],
    synneur:["Höglinger et al. 2024, Lancet Neurol 23:191–204","https://doi.org/10.1016/S1474-4422(23)00404-0"],
    nalls:["Nalls et al. 2019, Lancet Neurol 18:1091–1102","https://doi.org/10.1016/S1474-4422(19)30320-5"],
    kim:["Kim et al. 2024, Nat Genet 56:27–36","https://doi.org/10.1038/s41588-023-01584-8"],
    akcimen:["Akçimen et al. 2026, Brain 149:awaf379","https://doi.org/10.1093/brain/awaf379"],
    aan:["Pringsheim et al. 2021, Neurology 97:942–957","https://doi.org/10.1212/WNL.0000000000012868"],
    elldopa:["Fahn et al. 2004, N Engl J Med 351:2498–2508","https://doi.org/10.1056/NEJMoa033447"],
    dbs:["Deuschl et al. 2006, N Engl J Med 355:896–908","https://doi.org/10.1056/NEJMoa060281"],
    rivastigmine:["Emre et al. 2004, N Engl J Med 351:2509–2518","https://doi.org/10.1056/NEJMoa041470"],
    lixisenatide:["Meissner et al. 2024, N Engl J Med 390:1176–1185","https://doi.org/10.1056/NEJMoa2312323"],
    prasinezumab:["Pagano et al. 2022, N Engl J Med 387:421–432","https://doi.org/10.1056/NEJMoa2202867"],
    nice:["NICE NG71 2017, last reviewed 2024","https://www.nice.org.uk/guidance/ng71"]
  };
  const articleList = [
    { id: "ckd-definition", section:"def", title:"어떻게 정의하고 분류하는가?", aliases:["Parkinson disease","파킨슨병","parkinsonism","Lewy pathology"],
      summary:"PD — bradykinesia 중심의 임상 질환이자 흑질 도파민 신경 소실·α-synuclein Lewy 병리의 신경퇴행 축",
      facts:[["임상 핵심","bradykinesia + rest tremor 또는 rigidity","MDS criteria","2015",false],["병리 핵심","substantia nigra dopamine neuron loss + Lewy pathology","Poewe et al.","2017",false]],
      body:[["두 정의의 병치",["임상축 — 운동성 parkinsonism의 확인","병리축 — nigrostriatal degeneration·α-synuclein aggregation","생전 임상진단과 사후 병리확정의 구분"]],["분류 원칙",["idiopathic PD·유전성 PD·증상성 parkinsonism 분리","임상 확실성 established·probable의 단계화","생물학 분류는 연구용 프레임워크"]]], related:["ckd-differential","ckd-clinical-criteria","ckd-biological-definition"], papers:[P.poewe,P.mds] },
    { id: "ckd-differential", section:"def", title:"파킨슨증후군·비전형 질환과 무엇이 다른가?", aliases:["parkinsonism","MSA","PSP","CBD","drug-induced parkinsonism"],
      summary:"parkinsonism — 운동증후군 · PD — 그 원인 중 하나 · MSA·PSP·CBD·약물성·혈관성 원인의 별도 감별",
      facts:[["증후군 기준","bradykinesia + tremor 또는 rigidity","MDS criteria","2015",false],["한국 약물유발 parkinsonism 진료 포착","15.4/100,000명","Han et al.","2015",false]],
      body:[["범주 분리",["PD — 비대칭 발병·명확한 levodopa 반응·진행성 경과의 전형축","비전형 퇴행성 — MSA·PSP·CBD의 조기 자율신경·안구운동·피질 징후","이차성 — 약물·혈관·독성·구조성 원인"]],["해석 경계",["levodopa 반응 단독의 특이도 한계","초기 임상 중첩 → 종단 재평가","한국 약물유발 수치는 청구 정의의 진료 인원"]]], related:["ckd-definition","ckd-dx-differential","ckd-tests"], papers:[P.mds,P.han] },
    { id: "ckd-subtypes", section:"def", title:"주요 임상·생물학적 아형은 무엇인가?", aliases:["tremor dominant","PIGD","brain-first","body-first","genetic PD"],
      summary:"tremor-dominant·PIGD 임상형과 brain-first·body-first 병리모형 · GBA1·LRRK2 등 유전 층화의 서로 다른 축",
      facts:[["고침투 유전자","20개 이상","PD synthesis","2026",false],["monogenic 비중","약 5–10%","Blauwendraat et al.","2020",false]],
      body:[["임상 아형",["tremor-dominant·postural-instability/gait-difficulty 축","운동·인지·자율신경 부담의 조합","시간 경과에 따른 아형 이동 가능성"]],["생물학 아형",["brain-first·body-first — 병리 시작점 가설","GBA1·LRRK2·PRKN 등 유전자 기반 층화","임상형·병리형·유전형의 일대일 대응 금지"]]], related:["ckd-symptom-spectrum","ckd-genetics","ckd-heterogeneity"], papers:[P.poewe] },
    { id: "ckd-symptom-spectrum", section:"def", title:"운동·비운동 증상은 어떤 스펙트럼을 이루는가?", aliases:["motor symptoms","nonmotor symptoms","bradykinesia","autonomic","cognition"],
      summary:"운동완서·강직·안정떨림·보행장애의 운동축과 후각·수면·자율신경·기분·인지의 비운동축",
      facts:[["치매 누적","5년 17% · 10년 46% · 20년 83%","Aarsland et al.","2021",false],["진단핵심 운동징후","bradykinesia","MDS criteria","2015",false]],
      body:[["운동축",["bradykinesia·rigidity·rest tremor","postural instability·freezing·falls","약물 on/off에 따른 변동"]],["비운동축",["후각저하·REM수면행동·변비·기립저혈압","우울·불안·환시·인지저하","삶의 질과 돌봄부담의 독립 기여"]]], related:["ckd-early-symptoms","ckd-complications","ckd-nonmotor-tx"], papers:[P.poewe] },
    { id: "ckd-prevalence", section:"epi", title:"세계와 한국에서 얼마나 흔한가?", aliases:["prevalence","GBD","HIRA","NHIS","Korea"],
      summary:"GBD 2021 전 세계 1,176.7만명 · 한국 HIRA 2024 진료 인원 143,441명 · 임상문헌 65세 이상 2–3% — 정의·분모 혼용 금지",
      facts:[["전 세계 환자 수","11.767 million (95% UI 10.4–13.4)","GBD 2021 update","2021",false],["65세 이상 임상문헌","약 2–3%","Poewe et al.","2017",false],["한국 HIRA 진료 인원","143,441명","KDCA·HIRA","2024",false],["한국 HIRA 조작적 유병률","181.3/100,000명","Han et al.","2015",false]],
      body:[["수치의 층위",["GBD — 전 연령 모형 추계","2–3% — 65세 이상 임상문헌 범위","한국 143,441명 — 보험청구 진료 인원"]],["혼용 금지",["전 연령 모형·고령 임상표본·청구 포착값의 분모 차이","청구 진료 인원 ≠ 지역사회 유병률","연도·사례정의 없는 단순 증감 비교 금지"]]], related:["ckd-trend","ckd-demographics","ckd-burden"], papers:[P.gbd,P.han,P.poewe], links:[["KDCA 파킨슨병 현황 2025","https://www.kdca.go.kr/bbs/kdca/42/240708/download.do"]] },
    { id: "ckd-trend", section:"epi", title:"발생률·유병률과 미래 부담은 어떻게 변하는가?", aliases:["incidence","trend","forecast","2050","발생률"],
      summary:"2021년 발생 133.5만명 · 2050년 유병 2,520만명 전망 · 한국 연령표준화 발생률 2003→2023 감소",
      facts:[["세계 발생","1.335 million (95% UI 1.200–1.490)","GBD 2021 update","2021",false],["2050 세계 유병","25.2 million (95% UI 21.7–30.1) · 2021 대비 +112%","Su et al.","2050 전망",false],["한국 연령표준화 발생률","16.6 → 11.4/100,000 person-years","Lee et al.","2003→2023",false],["한국 AAPC","−2.1% (95% CI −2.7~−1.5)","Lee et al.","2003→2023",false]],
      body:[["서로 다른 방향",["세계 절대 환자·발생 건수 증가","한국 연령표준화 발생률 감소","고령화·인구증가·진단포착과 개인위험의 분리"]],["전망 해석",["2050 모형 — 인구고령화 기여 89%","예측 유병률 267/100,000 · 연령표준화 216/100,000","전망과 관측의 혼용 금지"]]], related:["ckd-prevalence","ckd-demographics","ckd-burden"], papers:[P.gbd,P.forecast,P.koreaTrend] },
    { id: "ckd-demographics", section:"epi", title:"어떤 연령·성별·집단에서 많이 발생하는가?", aliases:["age","sex","male","female","demography"],
      summary:"고령에서 급증 · 세계 연령표준화 유병 남:여 2021년 1.46 · 한국 진료 인원은 70세 이상 중심",
      facts:[["세계 남:여 연령표준화 유병비","1.46","Su et al.","2021",false],["한국 70대 진료 구성","42,172명 · 37.9%","NHIS·KDCA","2022",false],["한국 80세 이상 진료 구성","40,603명 · 36.5%","NHIS·KDCA","2022",false]],
      body:[["연령축",["70대·80세 이상에 한국 진료 인원의 집중","고령에서 발생·유병 급증","생존·수진·진단 접근의 동시 영향"]],["성별·집단축",["세계 모형 — 남성 연령표준화 부담 우세","한국 청구연구 — 여성 환자 수 우세 가능","성비와 절대 진료 인원 혼용 금지"]]], related:["ckd-prevalence","ckd-trend","ckd-ancestry-risk"], papers:[P.forecast,P.han], links:[["KDCA 파킨슨병 현황 2025","https://www.kdca.go.kr/bbs/kdca/42/240708/download.do"]] },
    { id: "ckd-burden", section:"epi", title:"장애·사망·돌봄 부담은 얼마나 큰가?", aliases:["DALY","mortality","cost","caregiver burden","질병부담"],
      summary:"2021년 747.2만 DALY·38.8만 사망 · 한국 건강보험 진료비 2020년 5,482억원 · 가족 돌봄의 비계량 부담",
      facts:[["세계 DALY","7.472 million (95% UI 6.740–8.140)","GBD 2021 update","2021",false],["세계 사망","0.388 million (95% UI 0.347–0.417)","GBD 2021 update","2021",false],["한국 건강보험 진료비","4,376억원 → 5,482억원","NHIS·KDCA","2016→2020",false],["한국 연평균 진료비 증가","+5.8%","NHIS·KDCA","2016→2020",false]],
      body:[["부담의 구성",["운동·인지·자율신경 장애의 누적","낙상·연하장애·폐렴·치매의 의료 부담","보호자 시간·소득손실·장기돌봄의 사회 부담"]],["수치 경계",["DALY·사망 — GBD 모형 추계","한국 진료비 — 건강보험 청구 범위","비급여·비공식 돌봄비 제외 가능성"]]], related:["ckd-prevalence","ckd-trend","ckd-complications"], papers:[P.gbd], links:[["KDCA 파킨슨병 현황 2025","https://www.kdca.go.kr/bbs/kdca/42/240708/download.do"]] },
    { id: "ckd-riskfactors", section:"risk", title:"주요 위험인자는 무엇인가?", aliases:["risk factors","aging","pesticide","head injury","diabetes"],
      summary:"노화·남성·유전 배경의 확립축과 농약·용제·두부손상·대사질환의 관찰연관 축",
      facts:[["연령","가장 강한 인구학적 위험축","Poewe et al.","2017",false],["남성:여성","약 2:1 임상문헌","Poewe et al.","2017",false]],
      body:[["위험 층위",["노화·성별·가족력의 비가역 축","농약·용제·두부손상·대사상태의 환경·건강 축","유전자–환경 상호작용의 후보 구조"]],["인과 경계",["관찰연관 ≠ 개인 원인 확정","노출 측정오차·직업·생활습관 교란","단일 노출만으로 발생 설명 금지"]]], related:["ckd-genetics","ckd-protective-triggers","ckd-ancestry-risk"], papers:[P.poewe] },
    { id: "ckd-genetics", section:"risk", title:"희귀 고침투 변이와 흔한 변이는 각각 얼마나 기여하는가?", aliases:["monogenic PD","polygenic","GBA1","LRRK2","heritability"],
      summary:"20개 이상 고침투 유전자·monogenic 5–10%와 다수 common variant의 polygenic 위험이 공존하는 이중 구조",
      facts:[["monogenic 비중","약 5–10%","Blauwendraat et al.","2020",false],["고침투 유전자","20개 이상","PD synthesis","2026",false],["GWAS heritable risk 설명","16–36%","Nalls et al.","2019",false],["GWAS 독립 신호","90개","Nalls et al.","2019",false]],
      body:[["희귀변이 축",["SNCA·LRRK2·VPS35 — 우성 유전","PRKN·PINK1·DJ-1 — 열성·조기발병 축","GBA1 — penetrance가 불완전한 강한 위험유전자"]],["흔한변이 축",["각 변이의 작은 효과가 누적되는 polygenic 구조","현재 GWAS가 설명하지 못한 유전위험 잔존","유전율·설명분산·개인위험의 구분"]]], related:["ckd-subtypes","ckd-gwas","ckd-rare-variants"], papers:[P.nalls] },
    { id: "ckd-protective-triggers", section:"risk", title:"보호요인과 촉발요인은 무엇인가?", aliases:["protective factors","exercise","caffeine","smoking","trigger"],
      summary:"운동·카페인·요산·흡연의 역학적 보호연관과 농약·용제·두부손상의 위험연관 — 예방 처방으로의 직접 전환 금지",
      facts:[["운동","낮은 PD 위험과 관찰연관","Poewe et al.","2017",false],["카페인","낮은 PD 위험과 관찰연관","Poewe et al.","2017",false]],
      body:[["관찰 신호",["운동·카페인·높은 urate·흡연과 낮은 진단위험의 연관","농약·용제·두부손상과 높은 위험의 연관","prodromal 행동변화에 의한 역인과 가능성"]],["권고 경계",["흡연의 전신 위해 → 보호목적 권고 불가","카페인·urate의 치료효과 미확립","운동 — 전신건강·기능 유지의 별도 근거"]]], related:["ckd-riskfactors","ckd-prodromal","ckd-standard-tx"], papers:[P.poewe] },
    { id: "ckd-ancestry-risk", section:"risk", title:"ancestry에 따라 위험변이 스펙트럼은 어떻게 다른가?", aliases:["ancestry","cross-ancestry","African","GBA1","LRRK2"],
      summary:"유럽계 90 signal·다인종 78 loci·African/African admixed 희귀변이의 서로 다른 설계 — 숫자 직접 비교 금지",
      facts:[["다인종 GWAS","49,049 cases + 18,785 proxies + 2.46M controls","Kim et al.","2024",false],["다인종 loci","78 loci · 신규 후보 12개","Kim et al.","2024",false],["African 연구","710 cases + 11,827 controls","Akçimen et al.","2026",false],["African/African admixed GBA1 carrier","cases 4%","Akçimen et al.","2026",false]],
      body:[["집단별 관찰",["African 표본에서 유럽·Ashkenazi 대표 GBA1 변이 미검출","유럽·아시아 대표 LRRK2 변이 미검출","ancestry별 빈도·LD·variant spectrum의 차이"]],["혼용 금지",["90 signal ≠ 78 locus — 단위·표본·LD·설계 차이","부재 관찰 ≠ 집단 전체의 절대 부재","singletons 중심 결과의 replication 필요"]]], related:["ckd-genetics","ckd-gwas","ckd-rare-variants"], papers:[P.nalls,P.kim,P.akcimen] },
    { id: "ckd-prodromal", section:"course", title:"운동증상 전에는 어떤 변화가 일어나는가?", aliases:["prodromal PD","RBD","hyposmia","constipation","autonomic"],
      summary:"후각저하·REM수면행동장애·변비·자율신경·기분 변화가 운동진단 전 수년간 축적되는 전구기",
      facts:[["MDS prodromal criteria","Bayesian probability framework","Berg et al.","2015/2019",false],["운동진단 핵심","bradykinesia + tremor 또는 rigidity","MDS criteria","2015",false]],
      body:[["전구 표지",["REM수면행동장애·후각저하·변비","기립저혈압·우울·미세운동 변화","단일 표지보다 다중 likelihood ratio의 결합"]],["해석 경계",["전구 표지의 낮은 단독 특이도","확률적 연구기준과 임상 확진의 분리","예방치료 부재 상황의 윤리·불안 고려"]]], related:["ckd-early-symptoms","ckd-tests","ckd-biological-definition"], papers:[P.mds] },
    { id: "ckd-progression", section:"course", title:"도파민 신경 소실과 α-synuclein 병리는 어떻게 진행되는가?", aliases:["substantia nigra","dopamine","alpha-synuclein","Lewy body","basal ganglia"],
      summary:"흑질 도파민 신경 소실 → 선조체 도파민 저하 → direct·indirect 회로 불균형 · α-synuclein 응집과 Lewy 병리의 동반",
      facts:[["분자 병리","α-synuclein aggregation · Lewy pathology","Poewe et al.","2017",false],["해부학 핵심","substantia nigra pars compacta dopamine neuron loss","Poewe et al.","2017",false]],
      body:[["회로 변화",["도파민 소실 → direct pathway 촉진 감소·indirect pathway 억제 감소","GPi/SNr 출력 증가 → thalamocortical 운동 촉진 저하","bradykinesia·rigidity의 회로 기반"]],["병리 전개",["α-synuclein proteostasis 실패·응집","lysosome·vesicle trafficking 유전경로의 수렴","Braak·prion-like 전파 — 유용한 모형이나 모든 환자의 고정 순서 아님"]]], related:["ckd-definition","ckd-heterogeneity","ckd-gwas"], papers:[P.poewe] },
    { id: "ckd-heterogeneity", section:"course", title:"환자마다 진행속도와 표현형이 다른 이유는 무엇인가?", aliases:["heterogeneity","progression","phenotype","resilience"],
      summary:"유전 배경·α-synuclein 분포·동반병리·회로 보상·연령·치료반응의 조합에 따른 이질적 궤적",
      facts:[["GWAS 설명 위험","16–36%","Nalls et al.","2019",false],["PDD 누적","17%@5y · 46%@10y · 83%@20y","Aarsland et al.","2021",false]],
      body:[["변이 원천",["GBA1·LRRK2 등 유전 배경","cortical Lewy·amyloid·tau 동반병리","dopaminergic·cholinergic·noradrenergic 손상의 조합"]],["측정 원천",["운동형·인지형·자율신경형의 서로 다른 endpoint","약물 on/off·생존·탈락에 따른 관측 편향","집단 평균을 개인 예후로 직접 전환 금지"]]], related:["ckd-subtypes","ckd-progression","ckd-complications"], papers:[P.nalls] },
    { id: "ckd-complications", section:"course", title:"인지장애와 주요 합병증은 어떻게 전개되는가?", aliases:["PD-MCI","PDD","dyskinesia","falls","dysphagia"],
      summary:"SCD→PD-MCI→PDD의 인지축과 wearing-off·dyskinesia·낙상·연하·정신증의 합병증 축",
      facts:[["PDD 누적 5년","17%","Aarsland et al.","2021",false],["PDD 누적 10년","46%","Aarsland et al.","2021",false],["PDD 누적 20년","83%","Aarsland et al.","2021",false]],
      body:[["인지축",["초기 executive·visuospatial 취약성","cortical α-synuclein·basal forebrain cholinergic loss","amyloid·tau 동반병리의 가속 가능성"]],["합병증축",["levodopa exposure·질병진행과 운동변동·dyskinesia","postural instability·freezing → falls","dysphagia·autonomic failure·psychosis → 돌봄 복잡성"]]], related:["ckd-symptom-spectrum","ckd-nonmotor-tx","ckd-response-safety"], papers:[P.rivastigmine] },
    { id: "ckd-early-symptoms", section:"dx", title:"초기 증상은 무엇인가?", aliases:["early symptoms","bradykinesia","rest tremor","rigidity","RBD"],
      summary:"비대칭 bradykinesia·rigidity·rest tremor의 운동 신호와 후각·수면·변비·기분의 비운동 신호",
      facts:[["parkinsonism 핵심","bradykinesia + rest tremor 또는 rigidity","MDS criteria","2015",false],["진단 재평가","6–12개월 간격","NICE NG71","2017",false]],
      body:[["초기 운동신호",["동작 느림·미세운동 감소·작은 글씨","한쪽 rest tremor·rigidity·팔흔들림 감소","보행·자세 변화의 점진적 출현"]],["초기 비운동신호",["후각저하·REM수면행동·변비","우울·불안·피로·통증","단일 비운동증상만으로 PD 확진 금지"]]], related:["ckd-prodromal","ckd-clinical-criteria","ckd-tests"], papers:[P.mds,P.nice] },
    { id: "ckd-clinical-criteria", section:"dx", title:"현재 임상 진단 기준은 무엇인가?", aliases:["MDS criteria","clinically established PD","probable PD","red flags"],
      summary:"MDS 2015 — parkinsonism 확인 후 absolute exclusion·red flag·supportive criteria의 균형으로 established·probable 분류",
      facts:[["현행 MDS 기준","Mov Disord 30:1591–1601","Postuma et al.","2015",false],["두 확실성","clinically established · probable PD","MDS criteria","2015",false],["핵심 운동증후군","bradykinesia + rest tremor 또는 rigidity","MDS criteria","2015",false]],
      body:[["판정 흐름",["parkinsonism의 임상 확인","absolute exclusion criterion의 부재","red flag와 supportive criterion의 상쇄"]],["사용 경계",["expert clinical diagnosis를 benchmark로 한 기준","병리확정 기준 아님","새 비전형 징후 출현 시 진단 재검토"]]], related:["ckd-definition","ckd-dx-differential","ckd-biological-definition"], papers:[P.mds] },
    { id: "ckd-tests", section:"dx", title:"어떤 검사와 바이오마커를 사용하는가?", aliases:["DaT-SPECT","MRI","SAA","CSF","skin biopsy"],
      summary:"임상진찰이 중심 · MRI는 구조성·비전형 원인 감별 · DaT-SPECT는 presynaptic dopaminergic deficit · α-syn SAA는 연구축",
      facts:[["임상진단 특이도","최대 98%","PD synthesis","2026",false],["DaT-SPECT 적응 맥락","essential tremor와 parkinsonism 감별 곤란","NICE NG71","2017",false],["한국 SAA 임상 성능","확인 필요 — 동일 기준의 한국 독립 코호트 직접 검증","직접 분석 필요","",true]],
      body:[["검사 역할",["MRI — 종양·혈관·수두증·비전형 pattern 감별","DaT-SPECT — presynaptic dopaminergic deficit 확인·PD 원인 특이도 제한","CSF·피부 α-syn SAA — 병리 anchor 후보"]],["검사 경계",["정상 구조 MRI로 PD 배제 불가","DaT 저하로 PD와 비전형 퇴행성 parkinsonism 완전 분리 불가","SAA 양성의 질환경계·임상적용 조건 미완성"]]], related:["ckd-clinical-criteria","ckd-dx-differential","ckd-biological-definition"], papers:[P.nsd,P.synneur,P.nice] },
    { id: "ckd-dx-differential", section:"dx", title:"감별진단의 핵심 장벽은 무엇인가?", aliases:["diagnostic accuracy","MSA","PSP","CBD","DLB"],
      summary:"초기 운동징후 중첩·비전형 징후의 지연·biomarker 질환특이도 한계 → 종단 임상판단 필수",
      facts:[["임상진단 특이도","최대 98% · 민감도 제한","PD synthesis","2026",false],["정기 재검토","6–12개월","NICE NG71","2017",false]],
      body:[["오분류 원천",["MSA·PSP·CBD·DLB 초기 표현형의 중첩","약물성·혈관성·정상압수두증 등 이차 원인","levodopa 반응과 dopaminergic imaging의 비특이성"]],["해결 전략",["운동·안구운동·자율신경·인지의 반복 평가","MRI·DaT-SPECT·병력의 보조적 결합","진단 라벨보다 불확실성·red flag의 명시"]]], related:["ckd-differential","ckd-tests","ckd-clinical-criteria"], papers:[P.mds,P.nice] },
    { id: "ckd-biological-definition", section:"dx", title:"생물학적 정의 프레임워크는 무엇이 다른가?", aliases:["NSD-ISS","SynNeurGe","SAA","biological definition","staging"],
      summary:"NSD-ISS — S·D와 기능단계 · SynNeurGe — S·N·G 구성요소 · 공통 α-syn anchor와 서로 다른 유전 포함 기준",
      facts:[["NSD-ISS","Lancet Neurol 23:178–190","Simuni et al.","2024",false],["SynNeurGe","Lancet Neurol 23:191–204","Höglinger et al.","2024",false],["임상 적용","두 프레임워크 모두 연구용","Lancet Neurology","2024",false]],
      body:[["공통점",["pathological α-synuclein의 S 축","dopaminergic dysfunction·neurodegeneration의 보조축","증상 전 단계의 연구대상화"]],["차이와 모순",["NSD-ISS — SNCA pathogenic variant를 stage 0에 배치","SynNeurGe — S·N·G 세 요소의 조합","같은 환자의 유전 조건별 분류 차이 가능성 → 혼용 금지"]]], related:["ckd-clinical-criteria","ckd-tests","ckd-guideline-change"], papers:[P.nsd,P.synneur] },
    { id: "ckd-standard-tx", section:"tx", title:"현재 표준 약물치료는 무엇인가?", aliases:["levodopa","dopamine agonist","MAO-B inhibitor","COMT inhibitor"],
      summary:"levodopa 중심의 증상 치료 · 연령·기능·부작용 위험에 따른 dopamine agonist·MAO-B inhibitor 선택",
      facts:[["초기 운동효과","levodopa가 dopamine agonist보다 우수","AAN guideline","2021",false],["ELLDOPA UPDRS 42주","placebo +7.8 · levodopa 600 mg/day −1.4","Fahn et al.","2004",false]],
      body:[["초기 선택",["운동증상이 삶의 질을 침범 → levodopa 우선","일부 젊은 환자 → dopamine agonist·MAO-B inhibitor 고려","최저 유효용량·개별 목표의 반복 조정"]],["보조 약물",["wearing-off → COMT·MAO-B inhibitor·dopamine agonist","tremor·dystonia·gait의 증상별 조합","증상 개선 ≠ 질병 진행 억제"]]], related:["ckd-fluctuation-dbs","ckd-response-safety","ckd-unmet"], papers:[P.aan,P.elldopa,P.nice] },
    { id: "ckd-fluctuation-dbs", section:"tx", title:"운동 합병증과 DBS는 어떻게 관리하는가?", aliases:["wearing-off","dyskinesia","deep brain stimulation","STN","GPi"],
      summary:"복용 간격·보조약·지속전달 조정 뒤 levodopa 반응성 severe motor complication에서 STN/GPi DBS 고려",
      facts:[["DBS PDQ-39 개선","평균 9.5점","Deuschl et al.","2006",false],["DBS off-med UPDRS-III 개선","평균 19.6점","Deuschl et al.","2006",false],["serious adverse event","DBS 13% vs 약물 4%","Deuschl et al.","2006",false]],
      body:[["단계적 관리",["복용 시간·식사·off pattern의 확인","levodopa fractionation·보조약·지속전달 치료","적절한 인지·정신·수술위험 평가 후 DBS"]],["DBS 경계",["levodopa 반응성 운동증상의 강한 개선","치매·중증 정신증·levodopa 비반응 axial symptom의 제한","출혈·감염·인지·기분·장치 합병증"]]], related:["ckd-standard-tx","ckd-response-safety","ckd-complications"], papers:[P.dbs,P.nice] },
    { id: "ckd-nonmotor-tx", section:"tx", title:"인지·비운동 증상은 어떻게 치료하는가?", aliases:["rivastigmine","PDD","psychosis","autonomic","rehabilitation"],
      summary:"PDD의 rivastigmine·증상별 정신증·우울·수면·자율신경 관리와 운동·물리·작업·언어 재활의 결합",
      facts:[["rivastigmine ADAS-cog","2.1점 개선 vs placebo 0.7점 악화","Emre et al.","2004",false],["rivastigmine 임상개선","19.8% vs 14.5%","Emre et al.","2004",false],["nausea","29.0% vs 11.2%","Emre et al.","2004",false],["vomiting","16.6% vs 1.7%","Emre et al.","2004",false]],
      body:[["약물축",["PDD → rivastigmine의 moderate cognitive benefit","psychosis → 유발약 검토·운동악화가 적은 약제 선택","우울·수면·기립저혈압·변비의 증상별 치료"]],["비약물축",["규칙적 운동·물리·작업치료","speech·swallow 평가와 cueing","환자·보호자 교육·낙상·운전·돌봄계획"]]], related:["ckd-complications","ckd-response-safety","ckd-standard-tx"], papers:[P.rivastigmine,P.nice] },
    { id: "ckd-response-safety", section:"tx", title:"치료반응과 부작용은 어떻게 균형 잡는가?", aliases:["dyskinesia","impulse control disorder","hallucination","somnolence","safety"],
      summary:"levodopa의 큰 운동효과·dyskinesia 위험과 dopamine agonist의 impulse control·환각·졸림 위험을 개인별 균형화",
      facts:[["levodopa dyskinesia 위험차","2년 +18.7% (95% CI 13.7–23.8)","AAN guideline","2021",false],["4년 위험차","+29.2% (95% CI 19.6–38.8)","AAN guideline","2021",false],["ELLDOPA 고용량","dyskinesia·nausea 등 증가","Fahn et al.","2004",false]],
      body:[["선택의 균형",["levodopa — 우수한 운동효과·장기 dyskinesia 가능성","dopamine agonist — 낮은 초기 dyskinesia·높은 impulse control·환각·졸림 위험","연령·인지·직업·운전·낙상 위험의 반영"]],["모니터링",["충동구매·도박·과식·성행동의 환자·가족 확인","환각·daytime sleepiness·기립저혈압 점검","갑작스러운 약물중단 회피"]]], related:["ckd-standard-tx","ckd-fluctuation-dbs","ckd-nonmotor-tx"], papers:[P.aan,P.elldopa] },
    { id: "ckd-unmet", section:"tx", title:"질병 진행을 늦추는 치료는 어디까지 왔는가?", aliases:["disease modification","lixisenatide","prasinezumab","alpha-synuclein","GLP-1"],
      summary:"승인된 disease-modifying therapy 부재 · lixisenatide phase 2 신호와 위장관 독성 · prasinezumab phase 2 일차종점 실패",
      facts:[["lixisenatide MDS-UPDRS III","12개월 −0.04 vs +3.04 · 차이 3.08","Meissner et al.","2024",false],["lixisenatide nausea·vomiting","46% · 13%","Meissner et al.","2024",false],["prasinezumab 저용량 변화","7.4 vs placebo 9.4 · P=0.24","Pagano et al.","2022",false],["prasinezumab infusion reaction","19.0%·34.0%","Pagano et al.","2022",false]],
      body:[["현재 신호",["GLP-1 agonist lixisenatide — 작은 phase 2 motor signal","anti-α-syn prasinezumab — global primary endpoint 미충족","symptomatic benefit과 neuroprotection의 분리"]],["확증 조건",["더 큰 phase 3·긴 washout·biomarker-anchored trial","subgroup exploratory 결과의 과대해석 금지","exenatide phase 3 논문의 2026 Expression of Concern 반영"]]], related:["ckd-standard-tx","ckd-drug-update","ckd-biological-definition"], papers:[P.lixisenatide,P.prasinezumab] },
    { id: "ckd-gwas", section:"omics", title:"GWAS는 어떤 유전자와 경로를 지목하는가?", aliases:["GWAS","SNCA","LRRK2","GBA1","lysosome"],
      summary:"유럽계 90 independent signal·78 genomic region과 다인종 78 loci → lysosome·vesicle trafficking·immune·neuronal pathway",
      facts:[["유럽계 표본","37,688 cases + 18,618 proxies + 1.41M controls","Nalls et al.","2019",false],["독립 신호·영역","90 signals · 78 regions · 38 novel","Nalls et al.","2019",false],["설명 heritable risk","16–36%","Nalls et al.","2019",false],["다인종 loci","78 loci · 신규 후보 12개","Kim et al.","2024",false]],
      body:[["경로 수렴",["SNCA·LRRK2·GBA1·TMEM175의 lysosomal 축","vesicle trafficking·mitochondrial·immune pathway","gene expression·methylation MR의 후보 유전자 지목"]],["비교 경계",["Nalls 90 signal과 Kim 78 locus의 단위 차이","표본·ancestry·LD·분석 설계 차이","locus association ≠ 인과변이·약물표적"]]], related:["ckd-genetics","ckd-ancestry-risk","ckd-variant-celltype"], papers:[P.nalls,P.kim] },
    { id: "ckd-rare-variants", section:"omics", title:"희귀변이·CNV·STR은 무엇을 더 보여주는가?", aliases:["rare variant","CNV","STR","PRKN","ATXN3"],
      summary:"SNV·indel 밖의 PRKN CNV·ATXN3 expansion과 ancestry-specific rare variant → short-read GWAS가 놓친 유전구조",
      facts:[["African rare variant","443개 · novel 182개","Akçimen et al.","2026",false],["PRKN CNV","cases 0.7%","Akçimen et al.","2026",false],["ATXN3 >45 CAG","3 cases + 1 unaffected control","Akçimen et al.","2026",false],["분석 유전자","51개 PD·신경퇴행 유전자","Akçimen et al.","2026",false]],
      body:[["추가 변이층",["coding·splicing rare SNV/indel","exon-level CNV·structural variation","repeat expansion·intermediate repeat"]],["증거 한계",["후보 대부분 singleton","플랫폼별 자료 → joint calling 부재","single-variant association·gene burden test 미수행 → 병원성 확정 금지"]]], related:["ckd-ancestry-risk","ckd-gwas","ckd-new-method"], papers:[P.akcimen] },
    { id: "ckd-variant-celltype", section:"omics", title:"위험변이는 어떤 세포·조직에서 작동하는가?", aliases:["eQTL","methylation QTL","MR","cell type","brain"],
      summary:"70개 GWAS signal의 expression·methylation MR과 뇌·특정 neuronal cell type enrichment → locus에서 작동세포로",
      facts:[["MR 대상","70 GWAS signals","Nalls et al.","2019",false],["fine-mapped causal variant","6개","Kim et al.","2024",false],["eQTL 지목 유전자","25개","Kim et al.","2024",false]],
      body:[["연결 사다리",["fine-mapping → credible variant","brain eQTL·methylation QTL → candidate gene","cell-type enrichment → 작동세포 우선순위"]],["해석 경계",["adult bulk brain QTL의 세포조성 혼합","질병상태·뇌영역·발달시점의 맥락 의존성","MR·colocalization 후보의 기능검증 필요"]]], related:["ckd-gwas","ckd-multiomics","ckd-new-method"], papers:[P.nalls,P.kim] },
    { id: "ckd-multiomics", section:"omics", title:"multi-omics와 single-cell 연구는 무엇을 보여주는가?", aliases:["multi-omics","single-cell","transcriptome","epigenome","proteome"],
      summary:"GWAS·QTL·single-cell·proteome의 결합 → lysosomal pathway와 신경세포 맥락의 세분화 · 인과방향은 별도 검증",
      facts:[["다인종 eQTL 후보","25 genes","Kim et al.","2024",false],["Nalls novel signals","38개","Nalls et al.","2019",false],["한국인 PD 종단 multi-omics 규모","확인 필요 — BRIDGE·PD cohort의 공개 자료 직접 확인","직접 조사 필요","",true]],
      body:[["얻는 정보",["bulk omics — 평균 pathway·조직 신호","single-cell — cell type·state별 발현 변화","genetics+QTL — 위험변이와 조절효과의 연결"]],["남은 장벽",["사후·횡단 자료의 원인·결과 혼재","세포조성·batch·medication 교란","ancestry·뇌영역·질병단계별 replication"]]], related:["ckd-variant-celltype","ckd-new-data","ckd-new-method"], papers:[P.nalls,P.kim] },
    { id: "ckd-guideline-change", section:"now", title:"진료 권고는 최근 어떻게 바뀌었는가?", aliases:["guideline","NICE NG71","AAN 2021","MDS criteria"],
      summary:"MDS 임상기준 2015 유지 · NICE NG71 2017판의 2024 검토 · AAN 2021 초기 dopaminergic therapy 권고",
      facts:[["MDS 진단 기준","2015 발행","Postuma et al.","2015",false],["NICE NG71","2017 발행 · 2024-12-19 검토","NICE","2017/2024",false],["AAN 초기 약물지침","Neurology 97:942–957","Pringsheim et al.","2021",false],["NICE 개정 주기","새 근거가 권고를 바꿀 때 review","NICE","2024",false]],
      body:[["권고 변화",["초기 운동치료에서 levodopa의 우수한 motor benefit 명시","dopamine agonist의 impulse control·환각·졸림 위험 강조","생물학 정의는 임상권고가 아닌 연구분류"]],["갱신 추적",["NICE — 고정 주기 아님·surveillance trigger 방식","MDS 기준 — continuous revision 필요성 명시","발행일·마지막 검토일·실제 권고 변경의 분리"]]], related:["ckd-clinical-criteria","ckd-standard-tx","ckd-biological-definition"], papers:[P.mds,P.nice,P.aan] },
    { id: "ckd-drug-update", section:"now", title:"새 치료제와 안전성 정보는 무엇인가?", aliases:["lixisenatide","prasinezumab","exenatide","PADOVA","safety"],
      summary:"lixisenatide phase 2 motor signal·위장관 독성 · prasinezumab PASADENA/PADOVA 일차종점 미충족 · exenatide 논문 우려표시",
      facts:[["lixisenatide 효과차","MDS-UPDRS III 3.08점 (95% CI 0.86–5.30)","Meissner et al.","2024",false],["prasinezumab PASADENA","primary endpoint 미충족","Pagano et al.","2022",false],["exenatide phase 3","Lancet Expression of Concern","Lancet editors","2026",false]],
      body:[["효과 신호",["GLP-1 class의 약제별 불일치","anti-α-syn antibody의 exploratory subgroup 신호","class effect·disease modification 확정 금지"]],["안전성·무결성",["lixisenatide nausea 46%·vomiting 13%","prasinezumab infusion reaction 19–34%","Expression of Concern 논문을 확정 근거에서 제외"]]], related:["ckd-unmet","ckd-response-safety","ckd-guideline-change"], papers:[P.lixisenatide,P.prasinezumab], links:[["Lancet exenatide Expression of Concern","https://doi.org/10.1016/S0140-6736(26)01241-9"]] },
    { id: "ckd-new-data", section:"now", title:"새 코호트·오믹스 데이터는 무엇이 생겼는가?", aliases:["cohort","multi-ancestry GWAS","African genetics","BRIDGE","PPMI"],
      summary:"2.46M controls의 multi-ancestry GWAS·African/African admixed rare-variant study·한국 BRIDGE·PD cohort 인프라",
      facts:[["다인종 총 대조","2.46 million","Kim et al.","2024",false],["African/African admixed","710 cases + 11,827 controls","Akçimen et al.","2026",false],["한국 인프라","BRIDGE·PD cohort 구축","KDCA","2025",false]],
      body:[["확장 방향",["European 중심 common-variant에서 multi-ancestry로 확장","SNV/indel에서 CNV·STR로 확장","임상 cohort와 biobank·omics의 연결"]],["사용 조건",["phenotype·ancestry·platform metadata의 정렬","summary statistics와 개인수준 자료의 접근 차이","한국 cohort의 공개범위·추적기간·multi-omics 규모 확인 필요"]]], related:["ckd-ancestry-risk","ckd-rare-variants","ckd-multiomics"], papers:[P.kim,P.akcimen], links:[["KDCA 파킨슨병 현황 2025","https://www.kdca.go.kr/bbs/kdca/42/240708/download.do"]] },
    { id: "ckd-new-method", section:"now", title:"새로 쓸 수 있게 된 분석 기법은 무엇인가?", aliases:["SAA","long-read","joint calling","single-cell QTL","spatial"],
      summary:"α-syn SAA·cross-ancestry fine-mapping·long-read·joint calling·single-cell QTL·spatial의 결합",
      facts:[["SAA 기반 분류","NSD-ISS·SynNeurGe","Lancet Neurology","2024",false],["fine-mapped causal variant","6개","Kim et al.","2024",false],["African 분석 미수행","joint calling·burden test","Akçimen et al.","2026",false]],
      body:[["방법 사다리",["SAA → 병리 anchor·시험대상 층화","fine-mapping·QTL → locus-to-gene","long-read·joint calling → CNV·STR·rare variant 해상도"]],["검증 우선순위",["single-cell·spatial → 작동세포·조직 위치","ancestry-matched reference·replication","assay 표준화·임상 유용성·비용효과의 독립 검증"]]], related:["ckd-tests","ckd-rare-variants","ckd-multiomics"], papers:[P.nsd,P.synneur,P.kim,P.akcimen] }
  ];

  const glossaryTerms = {
    "alpha-synuclein":{ key:"alpha-synuclein", definition: "PD의 Lewy 병리 핵심 단백질." },
    "lewy":{ key:"lewy", definition: "α-synuclein 응집 신경병리." },
    "bradykinesia":{ key:"bradykinesia", definition: "동작 속도·크기 감소." },
    "parkinsonism":{ key:"parkinsonism", definition: "PD를 포함하는 운동증후군." },
    "saa":{ key:"saa", definition: "병적 α-syn seed 증폭검사." },
    "gba1":{ key:"gba1", definition: "PD lysosomal 위험 유전자." },
    "lrrk2":{ key:"lrrk2", definition: "PD kinase 위험 유전자." },
    "dbs":{ key:"dbs", definition: "심부뇌자극 수술치료." },
    "pdd":{ key:"pdd", definition: "PD 경과 중 발생한 치매." },
    "gwas":{ key:"gwas", definition: "전장유전체 연관분석." },
    "cnv":{ key:"cnv", definition: "유전체 구간의 결실·중복." },
    "str":{ key:"str", definition: "짧은 연속반복 변이." },
    "eqtl":{ key:"eqtl", definition: "변이–유전자 발현 연관." },
    "ancestry":{ key:"ancestry", definition: "유전적 조상 배경." }
  };
  const glossaryPattern = /(^|[^A-Za-z0-9가-힣])(alpha-synuclein|Lewy|bradykinesia|parkinsonism|SAA|GBA1|LRRK2|DBS|PDD|GWAS|CNV|STR|eQTL|ancestry)(?=$|[^A-Za-z0-9])/gi;
  return { meta:meta, acts:acts, sections:sections, articles:articleList, glossaryTerms:glossaryTerms, glossaryPattern:glossaryPattern };
})();
